// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaveallowance"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaverequest"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"
)

// AbsenceTypeUpdate is the builder for updating AbsenceType entities.
type AbsenceTypeUpdate struct {
	config
	hooks     []Hook
	mutation  *AbsenceTypeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AbsenceTypeUpdate builder.
func (_u *AbsenceTypeUpdate) Where(ps ...predicate.AbsenceType) *AbsenceTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *AbsenceTypeUpdate) SetCreateBy(v uint32) *AbsenceTypeUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableCreateBy(v *uint32) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *AbsenceTypeUpdate) AddCreateBy(v int32) *AbsenceTypeUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *AbsenceTypeUpdate) ClearCreateBy() *AbsenceTypeUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *AbsenceTypeUpdate) SetUpdateBy(v uint32) *AbsenceTypeUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableUpdateBy(v *uint32) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *AbsenceTypeUpdate) AddUpdateBy(v int32) *AbsenceTypeUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *AbsenceTypeUpdate) ClearUpdateBy() *AbsenceTypeUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AbsenceTypeUpdate) SetUpdateTime(v time.Time) *AbsenceTypeUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableUpdateTime(v *time.Time) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *AbsenceTypeUpdate) ClearUpdateTime() *AbsenceTypeUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *AbsenceTypeUpdate) SetDeleteTime(v time.Time) *AbsenceTypeUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableDeleteTime(v *time.Time) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *AbsenceTypeUpdate) ClearDeleteTime() *AbsenceTypeUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *AbsenceTypeUpdate) SetName(v string) *AbsenceTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableName(v *string) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AbsenceTypeUpdate) SetDescription(v string) *AbsenceTypeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableDescription(v *string) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AbsenceTypeUpdate) ClearDescription() *AbsenceTypeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetColor sets the "color" field.
func (_u *AbsenceTypeUpdate) SetColor(v string) *AbsenceTypeUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableColor(v *string) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *AbsenceTypeUpdate) ClearColor() *AbsenceTypeUpdate {
	_u.mutation.ClearColor()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AbsenceTypeUpdate) SetIcon(v string) *AbsenceTypeUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableIcon(v *string) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *AbsenceTypeUpdate) ClearIcon() *AbsenceTypeUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetDeductsFromAllowance sets the "deducts_from_allowance" field.
func (_u *AbsenceTypeUpdate) SetDeductsFromAllowance(v bool) *AbsenceTypeUpdate {
	_u.mutation.SetDeductsFromAllowance(v)
	return _u
}

// SetNillableDeductsFromAllowance sets the "deducts_from_allowance" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableDeductsFromAllowance(v *bool) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetDeductsFromAllowance(*v)
	}
	return _u
}

// SetRequiresApproval sets the "requires_approval" field.
func (_u *AbsenceTypeUpdate) SetRequiresApproval(v bool) *AbsenceTypeUpdate {
	_u.mutation.SetRequiresApproval(v)
	return _u
}

// SetNillableRequiresApproval sets the "requires_approval" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableRequiresApproval(v *bool) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetRequiresApproval(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AbsenceTypeUpdate) SetIsActive(v bool) *AbsenceTypeUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableIsActive(v *bool) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AbsenceTypeUpdate) SetSortOrder(v int) *AbsenceTypeUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableSortOrder(v *int) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AbsenceTypeUpdate) AddSortOrder(v int) *AbsenceTypeUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AbsenceTypeUpdate) SetMetadata(v map[string]interface{}) *AbsenceTypeUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AbsenceTypeUpdate) ClearMetadata() *AbsenceTypeUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetRequiresSigning sets the "requires_signing" field.
func (_u *AbsenceTypeUpdate) SetRequiresSigning(v bool) *AbsenceTypeUpdate {
	_u.mutation.SetRequiresSigning(v)
	return _u
}

// SetNillableRequiresSigning sets the "requires_signing" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableRequiresSigning(v *bool) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetRequiresSigning(*v)
	}
	return _u
}

// SetSigningTemplateID sets the "signing_template_id" field.
func (_u *AbsenceTypeUpdate) SetSigningTemplateID(v string) *AbsenceTypeUpdate {
	_u.mutation.SetSigningTemplateID(v)
	return _u
}

// SetNillableSigningTemplateID sets the "signing_template_id" field if the given value is not nil.
func (_u *AbsenceTypeUpdate) SetNillableSigningTemplateID(v *string) *AbsenceTypeUpdate {
	if v != nil {
		_u.SetSigningTemplateID(*v)
	}
	return _u
}

// ClearSigningTemplateID clears the value of the "signing_template_id" field.
func (_u *AbsenceTypeUpdate) ClearSigningTemplateID() *AbsenceTypeUpdate {
	_u.mutation.ClearSigningTemplateID()
	return _u
}

// AddLeaveAllowanceIDs adds the "leave_allowances" edge to the LeaveAllowance entity by IDs.
func (_u *AbsenceTypeUpdate) AddLeaveAllowanceIDs(ids ...string) *AbsenceTypeUpdate {
	_u.mutation.AddLeaveAllowanceIDs(ids...)
	return _u
}

// AddLeaveAllowances adds the "leave_allowances" edges to the LeaveAllowance entity.
func (_u *AbsenceTypeUpdate) AddLeaveAllowances(v ...*LeaveAllowance) *AbsenceTypeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaveAllowanceIDs(ids...)
}

// AddLeaveRequestIDs adds the "leave_requests" edge to the LeaveRequest entity by IDs.
func (_u *AbsenceTypeUpdate) AddLeaveRequestIDs(ids ...string) *AbsenceTypeUpdate {
	_u.mutation.AddLeaveRequestIDs(ids...)
	return _u
}

// AddLeaveRequests adds the "leave_requests" edges to the LeaveRequest entity.
func (_u *AbsenceTypeUpdate) AddLeaveRequests(v ...*LeaveRequest) *AbsenceTypeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaveRequestIDs(ids...)
}

// Mutation returns the AbsenceTypeMutation object of the builder.
func (_u *AbsenceTypeUpdate) Mutation() *AbsenceTypeMutation {
	return _u.mutation
}

// ClearLeaveAllowances clears all "leave_allowances" edges to the LeaveAllowance entity.
func (_u *AbsenceTypeUpdate) ClearLeaveAllowances() *AbsenceTypeUpdate {
	_u.mutation.ClearLeaveAllowances()
	return _u
}

// RemoveLeaveAllowanceIDs removes the "leave_allowances" edge to LeaveAllowance entities by IDs.
func (_u *AbsenceTypeUpdate) RemoveLeaveAllowanceIDs(ids ...string) *AbsenceTypeUpdate {
	_u.mutation.RemoveLeaveAllowanceIDs(ids...)
	return _u
}

// RemoveLeaveAllowances removes "leave_allowances" edges to LeaveAllowance entities.
func (_u *AbsenceTypeUpdate) RemoveLeaveAllowances(v ...*LeaveAllowance) *AbsenceTypeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaveAllowanceIDs(ids...)
}

// ClearLeaveRequests clears all "leave_requests" edges to the LeaveRequest entity.
func (_u *AbsenceTypeUpdate) ClearLeaveRequests() *AbsenceTypeUpdate {
	_u.mutation.ClearLeaveRequests()
	return _u
}

// RemoveLeaveRequestIDs removes the "leave_requests" edge to LeaveRequest entities by IDs.
func (_u *AbsenceTypeUpdate) RemoveLeaveRequestIDs(ids ...string) *AbsenceTypeUpdate {
	_u.mutation.RemoveLeaveRequestIDs(ids...)
	return _u
}

// RemoveLeaveRequests removes "leave_requests" edges to LeaveRequest entities.
func (_u *AbsenceTypeUpdate) RemoveLeaveRequests(v ...*LeaveRequest) *AbsenceTypeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaveRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AbsenceTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AbsenceTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AbsenceTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AbsenceTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AbsenceTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := absencetype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AbsenceType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := absencetype.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "AbsenceType.color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := absencetype.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "AbsenceType.icon": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AbsenceTypeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AbsenceTypeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AbsenceTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(absencetype.Table, absencetype.Columns, sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(absencetype.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(absencetype.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(absencetype.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(absencetype.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(absencetype.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(absencetype.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(absencetype.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(absencetype.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(absencetype.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(absencetype.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(absencetype.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(absencetype.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(absencetype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(absencetype.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(absencetype.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(absencetype.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(absencetype.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(absencetype.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(absencetype.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.DeductsFromAllowance(); ok {
		_spec.SetField(absencetype.FieldDeductsFromAllowance, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequiresApproval(); ok {
		_spec.SetField(absencetype.FieldRequiresApproval, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(absencetype.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(absencetype.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(absencetype.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(absencetype.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(absencetype.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequiresSigning(); ok {
		_spec.SetField(absencetype.FieldRequiresSigning, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SigningTemplateID(); ok {
		_spec.SetField(absencetype.FieldSigningTemplateID, field.TypeString, value)
	}
	if _u.mutation.SigningTemplateIDCleared() {
		_spec.ClearField(absencetype.FieldSigningTemplateID, field.TypeString)
	}
	if _u.mutation.LeaveAllowancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaveallowance.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeaveAllowancesIDs(); len(nodes) > 0 && !_u.mutation.LeaveAllowancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaveallowance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaveAllowancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaveallowance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeaveRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeaveRequestsIDs(); len(nodes) > 0 && !_u.mutation.LeaveRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaveRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{absencetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AbsenceTypeUpdateOne is the builder for updating a single AbsenceType entity.
type AbsenceTypeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AbsenceTypeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *AbsenceTypeUpdateOne) SetCreateBy(v uint32) *AbsenceTypeUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableCreateBy(v *uint32) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *AbsenceTypeUpdateOne) AddCreateBy(v int32) *AbsenceTypeUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *AbsenceTypeUpdateOne) ClearCreateBy() *AbsenceTypeUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *AbsenceTypeUpdateOne) SetUpdateBy(v uint32) *AbsenceTypeUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableUpdateBy(v *uint32) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *AbsenceTypeUpdateOne) AddUpdateBy(v int32) *AbsenceTypeUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *AbsenceTypeUpdateOne) ClearUpdateBy() *AbsenceTypeUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AbsenceTypeUpdateOne) SetUpdateTime(v time.Time) *AbsenceTypeUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableUpdateTime(v *time.Time) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *AbsenceTypeUpdateOne) ClearUpdateTime() *AbsenceTypeUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *AbsenceTypeUpdateOne) SetDeleteTime(v time.Time) *AbsenceTypeUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableDeleteTime(v *time.Time) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *AbsenceTypeUpdateOne) ClearDeleteTime() *AbsenceTypeUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *AbsenceTypeUpdateOne) SetName(v string) *AbsenceTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableName(v *string) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AbsenceTypeUpdateOne) SetDescription(v string) *AbsenceTypeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableDescription(v *string) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AbsenceTypeUpdateOne) ClearDescription() *AbsenceTypeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetColor sets the "color" field.
func (_u *AbsenceTypeUpdateOne) SetColor(v string) *AbsenceTypeUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableColor(v *string) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *AbsenceTypeUpdateOne) ClearColor() *AbsenceTypeUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AbsenceTypeUpdateOne) SetIcon(v string) *AbsenceTypeUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableIcon(v *string) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *AbsenceTypeUpdateOne) ClearIcon() *AbsenceTypeUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetDeductsFromAllowance sets the "deducts_from_allowance" field.
func (_u *AbsenceTypeUpdateOne) SetDeductsFromAllowance(v bool) *AbsenceTypeUpdateOne {
	_u.mutation.SetDeductsFromAllowance(v)
	return _u
}

// SetNillableDeductsFromAllowance sets the "deducts_from_allowance" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableDeductsFromAllowance(v *bool) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetDeductsFromAllowance(*v)
	}
	return _u
}

// SetRequiresApproval sets the "requires_approval" field.
func (_u *AbsenceTypeUpdateOne) SetRequiresApproval(v bool) *AbsenceTypeUpdateOne {
	_u.mutation.SetRequiresApproval(v)
	return _u
}

// SetNillableRequiresApproval sets the "requires_approval" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableRequiresApproval(v *bool) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetRequiresApproval(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AbsenceTypeUpdateOne) SetIsActive(v bool) *AbsenceTypeUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableIsActive(v *bool) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AbsenceTypeUpdateOne) SetSortOrder(v int) *AbsenceTypeUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableSortOrder(v *int) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AbsenceTypeUpdateOne) AddSortOrder(v int) *AbsenceTypeUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AbsenceTypeUpdateOne) SetMetadata(v map[string]interface{}) *AbsenceTypeUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AbsenceTypeUpdateOne) ClearMetadata() *AbsenceTypeUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetRequiresSigning sets the "requires_signing" field.
func (_u *AbsenceTypeUpdateOne) SetRequiresSigning(v bool) *AbsenceTypeUpdateOne {
	_u.mutation.SetRequiresSigning(v)
	return _u
}

// SetNillableRequiresSigning sets the "requires_signing" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableRequiresSigning(v *bool) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetRequiresSigning(*v)
	}
	return _u
}

// SetSigningTemplateID sets the "signing_template_id" field.
func (_u *AbsenceTypeUpdateOne) SetSigningTemplateID(v string) *AbsenceTypeUpdateOne {
	_u.mutation.SetSigningTemplateID(v)
	return _u
}

// SetNillableSigningTemplateID sets the "signing_template_id" field if the given value is not nil.
func (_u *AbsenceTypeUpdateOne) SetNillableSigningTemplateID(v *string) *AbsenceTypeUpdateOne {
	if v != nil {
		_u.SetSigningTemplateID(*v)
	}
	return _u
}

// ClearSigningTemplateID clears the value of the "signing_template_id" field.
func (_u *AbsenceTypeUpdateOne) ClearSigningTemplateID() *AbsenceTypeUpdateOne {
	_u.mutation.ClearSigningTemplateID()
	return _u
}

// AddLeaveAllowanceIDs adds the "leave_allowances" edge to the LeaveAllowance entity by IDs.
func (_u *AbsenceTypeUpdateOne) AddLeaveAllowanceIDs(ids ...string) *AbsenceTypeUpdateOne {
	_u.mutation.AddLeaveAllowanceIDs(ids...)
	return _u
}

// AddLeaveAllowances adds the "leave_allowances" edges to the LeaveAllowance entity.
func (_u *AbsenceTypeUpdateOne) AddLeaveAllowances(v ...*LeaveAllowance) *AbsenceTypeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaveAllowanceIDs(ids...)
}

// AddLeaveRequestIDs adds the "leave_requests" edge to the LeaveRequest entity by IDs.
func (_u *AbsenceTypeUpdateOne) AddLeaveRequestIDs(ids ...string) *AbsenceTypeUpdateOne {
	_u.mutation.AddLeaveRequestIDs(ids...)
	return _u
}

// AddLeaveRequests adds the "leave_requests" edges to the LeaveRequest entity.
func (_u *AbsenceTypeUpdateOne) AddLeaveRequests(v ...*LeaveRequest) *AbsenceTypeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeaveRequestIDs(ids...)
}

// Mutation returns the AbsenceTypeMutation object of the builder.
func (_u *AbsenceTypeUpdateOne) Mutation() *AbsenceTypeMutation {
	return _u.mutation
}

// ClearLeaveAllowances clears all "leave_allowances" edges to the LeaveAllowance entity.
func (_u *AbsenceTypeUpdateOne) ClearLeaveAllowances() *AbsenceTypeUpdateOne {
	_u.mutation.ClearLeaveAllowances()
	return _u
}

// RemoveLeaveAllowanceIDs removes the "leave_allowances" edge to LeaveAllowance entities by IDs.
func (_u *AbsenceTypeUpdateOne) RemoveLeaveAllowanceIDs(ids ...string) *AbsenceTypeUpdateOne {
	_u.mutation.RemoveLeaveAllowanceIDs(ids...)
	return _u
}

// RemoveLeaveAllowances removes "leave_allowances" edges to LeaveAllowance entities.
func (_u *AbsenceTypeUpdateOne) RemoveLeaveAllowances(v ...*LeaveAllowance) *AbsenceTypeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaveAllowanceIDs(ids...)
}

// ClearLeaveRequests clears all "leave_requests" edges to the LeaveRequest entity.
func (_u *AbsenceTypeUpdateOne) ClearLeaveRequests() *AbsenceTypeUpdateOne {
	_u.mutation.ClearLeaveRequests()
	return _u
}

// RemoveLeaveRequestIDs removes the "leave_requests" edge to LeaveRequest entities by IDs.
func (_u *AbsenceTypeUpdateOne) RemoveLeaveRequestIDs(ids ...string) *AbsenceTypeUpdateOne {
	_u.mutation.RemoveLeaveRequestIDs(ids...)
	return _u
}

// RemoveLeaveRequests removes "leave_requests" edges to LeaveRequest entities.
func (_u *AbsenceTypeUpdateOne) RemoveLeaveRequests(v ...*LeaveRequest) *AbsenceTypeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeaveRequestIDs(ids...)
}

// Where appends a list predicates to the AbsenceTypeUpdate builder.
func (_u *AbsenceTypeUpdateOne) Where(ps ...predicate.AbsenceType) *AbsenceTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AbsenceTypeUpdateOne) Select(field string, fields ...string) *AbsenceTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AbsenceType entity.
func (_u *AbsenceTypeUpdateOne) Save(ctx context.Context) (*AbsenceType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AbsenceTypeUpdateOne) SaveX(ctx context.Context) *AbsenceType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AbsenceTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AbsenceTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AbsenceTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := absencetype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AbsenceType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := absencetype.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "AbsenceType.color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := absencetype.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "AbsenceType.icon": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AbsenceTypeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AbsenceTypeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AbsenceTypeUpdateOne) sqlSave(ctx context.Context) (_node *AbsenceType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(absencetype.Table, absencetype.Columns, sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AbsenceType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, absencetype.FieldID)
		for _, f := range fields {
			if !absencetype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != absencetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(absencetype.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(absencetype.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(absencetype.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(absencetype.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(absencetype.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(absencetype.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(absencetype.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(absencetype.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(absencetype.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(absencetype.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(absencetype.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(absencetype.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(absencetype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(absencetype.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(absencetype.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(absencetype.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(absencetype.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(absencetype.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(absencetype.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.DeductsFromAllowance(); ok {
		_spec.SetField(absencetype.FieldDeductsFromAllowance, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequiresApproval(); ok {
		_spec.SetField(absencetype.FieldRequiresApproval, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(absencetype.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(absencetype.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(absencetype.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(absencetype.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(absencetype.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequiresSigning(); ok {
		_spec.SetField(absencetype.FieldRequiresSigning, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SigningTemplateID(); ok {
		_spec.SetField(absencetype.FieldSigningTemplateID, field.TypeString, value)
	}
	if _u.mutation.SigningTemplateIDCleared() {
		_spec.ClearField(absencetype.FieldSigningTemplateID, field.TypeString)
	}
	if _u.mutation.LeaveAllowancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaveallowance.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeaveAllowancesIDs(); len(nodes) > 0 && !_u.mutation.LeaveAllowancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaveallowance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaveAllowancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaveallowance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeaveRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeaveRequestsIDs(); len(nodes) > 0 && !_u.mutation.LeaveRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaveRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AbsenceType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{absencetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
