// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaveallowance"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaverequest"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"
)

// AbsenceTypeQuery is the builder for querying AbsenceType entities.
type AbsenceTypeQuery struct {
	config
	ctx                 *QueryContext
	order               []absencetype.OrderOption
	inters              []Interceptor
	predicates          []predicate.AbsenceType
	withLeaveAllowances *LeaveAllowanceQuery
	withLeaveRequests   *LeaveRequestQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AbsenceTypeQuery builder.
func (_q *AbsenceTypeQuery) Where(ps ...predicate.AbsenceType) *AbsenceTypeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AbsenceTypeQuery) Limit(limit int) *AbsenceTypeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AbsenceTypeQuery) Offset(offset int) *AbsenceTypeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AbsenceTypeQuery) Unique(unique bool) *AbsenceTypeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AbsenceTypeQuery) Order(o ...absencetype.OrderOption) *AbsenceTypeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLeaveAllowances chains the current query on the "leave_allowances" edge.
func (_q *AbsenceTypeQuery) QueryLeaveAllowances() *LeaveAllowanceQuery {
	query := (&LeaveAllowanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(absencetype.Table, absencetype.FieldID, selector),
			sqlgraph.To(leaveallowance.Table, leaveallowance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, absencetype.LeaveAllowancesTable, absencetype.LeaveAllowancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLeaveRequests chains the current query on the "leave_requests" edge.
func (_q *AbsenceTypeQuery) QueryLeaveRequests() *LeaveRequestQuery {
	query := (&LeaveRequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(absencetype.Table, absencetype.FieldID, selector),
			sqlgraph.To(leaverequest.Table, leaverequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, absencetype.LeaveRequestsTable, absencetype.LeaveRequestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AbsenceType entity from the query.
// Returns a *NotFoundError when no AbsenceType was found.
func (_q *AbsenceTypeQuery) First(ctx context.Context) (*AbsenceType, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{absencetype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AbsenceTypeQuery) FirstX(ctx context.Context) *AbsenceType {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AbsenceType ID from the query.
// Returns a *NotFoundError when no AbsenceType ID was found.
func (_q *AbsenceTypeQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{absencetype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AbsenceTypeQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AbsenceType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AbsenceType entity is found.
// Returns a *NotFoundError when no AbsenceType entities are found.
func (_q *AbsenceTypeQuery) Only(ctx context.Context) (*AbsenceType, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{absencetype.Label}
	default:
		return nil, &NotSingularError{absencetype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AbsenceTypeQuery) OnlyX(ctx context.Context) *AbsenceType {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AbsenceType ID in the query.
// Returns a *NotSingularError when more than one AbsenceType ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AbsenceTypeQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{absencetype.Label}
	default:
		err = &NotSingularError{absencetype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AbsenceTypeQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AbsenceTypes.
func (_q *AbsenceTypeQuery) All(ctx context.Context) ([]*AbsenceType, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AbsenceType, *AbsenceTypeQuery]()
	return withInterceptors[[]*AbsenceType](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AbsenceTypeQuery) AllX(ctx context.Context) []*AbsenceType {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AbsenceType IDs.
func (_q *AbsenceTypeQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(absencetype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AbsenceTypeQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AbsenceTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AbsenceTypeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AbsenceTypeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AbsenceTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AbsenceTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AbsenceTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AbsenceTypeQuery) Clone() *AbsenceTypeQuery {
	if _q == nil {
		return nil
	}
	return &AbsenceTypeQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]absencetype.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.AbsenceType{}, _q.predicates...),
		withLeaveAllowances: _q.withLeaveAllowances.Clone(),
		withLeaveRequests:   _q.withLeaveRequests.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithLeaveAllowances tells the query-builder to eager-load the nodes that are connected to
// the "leave_allowances" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AbsenceTypeQuery) WithLeaveAllowances(opts ...func(*LeaveAllowanceQuery)) *AbsenceTypeQuery {
	query := (&LeaveAllowanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLeaveAllowances = query
	return _q
}

// WithLeaveRequests tells the query-builder to eager-load the nodes that are connected to
// the "leave_requests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AbsenceTypeQuery) WithLeaveRequests(opts ...func(*LeaveRequestQuery)) *AbsenceTypeQuery {
	query := (&LeaveRequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLeaveRequests = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateBy uint32 `json:"create_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AbsenceType.Query().
//		GroupBy(absencetype.FieldCreateBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AbsenceTypeQuery) GroupBy(field string, fields ...string) *AbsenceTypeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AbsenceTypeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = absencetype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateBy uint32 `json:"create_by,omitempty"`
//	}
//
//	client.AbsenceType.Query().
//		Select(absencetype.FieldCreateBy).
//		Scan(ctx, &v)
func (_q *AbsenceTypeQuery) Select(fields ...string) *AbsenceTypeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AbsenceTypeSelect{AbsenceTypeQuery: _q}
	sbuild.label = absencetype.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AbsenceTypeSelect configured with the given aggregations.
func (_q *AbsenceTypeQuery) Aggregate(fns ...AggregateFunc) *AbsenceTypeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AbsenceTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !absencetype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if absencetype.Policy == nil {
		return errors.New("ent: uninitialized absencetype.Policy (forgotten import ent/runtime?)")
	}
	if err := absencetype.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *AbsenceTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AbsenceType, error) {
	var (
		nodes       = []*AbsenceType{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withLeaveAllowances != nil,
			_q.withLeaveRequests != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AbsenceType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AbsenceType{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLeaveAllowances; query != nil {
		if err := _q.loadLeaveAllowances(ctx, query, nodes,
			func(n *AbsenceType) { n.Edges.LeaveAllowances = []*LeaveAllowance{} },
			func(n *AbsenceType, e *LeaveAllowance) { n.Edges.LeaveAllowances = append(n.Edges.LeaveAllowances, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLeaveRequests; query != nil {
		if err := _q.loadLeaveRequests(ctx, query, nodes,
			func(n *AbsenceType) { n.Edges.LeaveRequests = []*LeaveRequest{} },
			func(n *AbsenceType, e *LeaveRequest) { n.Edges.LeaveRequests = append(n.Edges.LeaveRequests, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AbsenceTypeQuery) loadLeaveAllowances(ctx context.Context, query *LeaveAllowanceQuery, nodes []*AbsenceType, init func(*AbsenceType), assign func(*AbsenceType, *LeaveAllowance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AbsenceType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(leaveallowance.FieldAbsenceTypeID)
	}
	query.Where(predicate.LeaveAllowance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(absencetype.LeaveAllowancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AbsenceTypeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "absence_type_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AbsenceTypeQuery) loadLeaveRequests(ctx context.Context, query *LeaveRequestQuery, nodes []*AbsenceType, init func(*AbsenceType), assign func(*AbsenceType, *LeaveRequest)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AbsenceType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(leaverequest.FieldAbsenceTypeID)
	}
	query.Where(predicate.LeaveRequest(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(absencetype.LeaveRequestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AbsenceTypeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "absence_type_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AbsenceTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AbsenceTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(absencetype.Table, absencetype.Columns, sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, absencetype.FieldID)
		for i := range fields {
			if fields[i] != absencetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AbsenceTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(absencetype.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = absencetype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AbsenceTypeQuery) ForUpdate(opts ...sql.LockOption) *AbsenceTypeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AbsenceTypeQuery) ForShare(opts ...sql.LockOption) *AbsenceTypeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AbsenceTypeQuery) Modify(modifiers ...func(s *sql.Selector)) *AbsenceTypeSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AbsenceTypeGroupBy is the group-by builder for AbsenceType entities.
type AbsenceTypeGroupBy struct {
	selector
	build *AbsenceTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AbsenceTypeGroupBy) Aggregate(fns ...AggregateFunc) *AbsenceTypeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AbsenceTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AbsenceTypeQuery, *AbsenceTypeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AbsenceTypeGroupBy) sqlScan(ctx context.Context, root *AbsenceTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AbsenceTypeSelect is the builder for selecting fields of AbsenceType entities.
type AbsenceTypeSelect struct {
	*AbsenceTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AbsenceTypeSelect) Aggregate(fns ...AggregateFunc) *AbsenceTypeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AbsenceTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AbsenceTypeQuery, *AbsenceTypeSelect](ctx, _s.AbsenceTypeQuery, _s, _s.inters, v)
}

func (_s *AbsenceTypeSelect) sqlScan(ctx context.Context, root *AbsenceTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AbsenceTypeSelect) Modify(modifiers ...func(s *sql.Selector)) *AbsenceTypeSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
