// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
)

// AbsenceType is the model entity for the AbsenceType schema.
type AbsenceType struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Absence type name
	Name string `json:"name,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	// Hex color for calendar display
	Color string `json:"color,omitempty"`
	// Lucide icon name
	Icon string `json:"icon,omitempty"`
	// Whether this type consumes leave days
	DeductsFromAllowance bool `json:"deducts_from_allowance,omitempty"`
	// Whether requests need HR admin approval
	RequiresApproval bool `json:"requires_approval,omitempty"`
	// Whether this type is available for new requests
	IsActive bool `json:"is_active,omitempty"`
	// Display sort order
	SortOrder int `json:"sort_order,omitempty"`
	// Custom metadata (JSON)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Whether this type requires document signing
	RequiresSigning bool `json:"requires_signing,omitempty"`
	// Paperless signing template ID
	SigningTemplateID string `json:"signing_template_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AbsenceTypeQuery when eager-loading is set.
	Edges        AbsenceTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AbsenceTypeEdges holds the relations/edges for other nodes in the graph.
type AbsenceTypeEdges struct {
	// LeaveAllowances holds the value of the leave_allowances edge.
	LeaveAllowances []*LeaveAllowance `json:"leave_allowances,omitempty"`
	// LeaveRequests holds the value of the leave_requests edge.
	LeaveRequests []*LeaveRequest `json:"leave_requests,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LeaveAllowancesOrErr returns the LeaveAllowances value or an error if the edge
// was not loaded in eager-loading.
func (e AbsenceTypeEdges) LeaveAllowancesOrErr() ([]*LeaveAllowance, error) {
	if e.loadedTypes[0] {
		return e.LeaveAllowances, nil
	}
	return nil, &NotLoadedError{edge: "leave_allowances"}
}

// LeaveRequestsOrErr returns the LeaveRequests value or an error if the edge
// was not loaded in eager-loading.
func (e AbsenceTypeEdges) LeaveRequestsOrErr() ([]*LeaveRequest, error) {
	if e.loadedTypes[1] {
		return e.LeaveRequests, nil
	}
	return nil, &NotLoadedError{edge: "leave_requests"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AbsenceType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case absencetype.FieldMetadata:
			values[i] = new([]byte)
		case absencetype.FieldDeductsFromAllowance, absencetype.FieldRequiresApproval, absencetype.FieldIsActive, absencetype.FieldRequiresSigning:
			values[i] = new(sql.NullBool)
		case absencetype.FieldCreateBy, absencetype.FieldUpdateBy, absencetype.FieldTenantID, absencetype.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case absencetype.FieldID, absencetype.FieldName, absencetype.FieldDescription, absencetype.FieldColor, absencetype.FieldIcon, absencetype.FieldSigningTemplateID:
			values[i] = new(sql.NullString)
		case absencetype.FieldCreateTime, absencetype.FieldUpdateTime, absencetype.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AbsenceType fields.
func (_m *AbsenceType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case absencetype.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case absencetype.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case absencetype.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case absencetype.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case absencetype.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case absencetype.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case absencetype.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case absencetype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case absencetype.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case absencetype.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case absencetype.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case absencetype.FieldDeductsFromAllowance:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deducts_from_allowance", values[i])
			} else if value.Valid {
				_m.DeductsFromAllowance = value.Bool
			}
		case absencetype.FieldRequiresApproval:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field requires_approval", values[i])
			} else if value.Valid {
				_m.RequiresApproval = value.Bool
			}
		case absencetype.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case absencetype.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case absencetype.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case absencetype.FieldRequiresSigning:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field requires_signing", values[i])
			} else if value.Valid {
				_m.RequiresSigning = value.Bool
			}
		case absencetype.FieldSigningTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signing_template_id", values[i])
			} else if value.Valid {
				_m.SigningTemplateID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AbsenceType.
// This includes values selected through modifiers, order, etc.
func (_m *AbsenceType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLeaveAllowances queries the "leave_allowances" edge of the AbsenceType entity.
func (_m *AbsenceType) QueryLeaveAllowances() *LeaveAllowanceQuery {
	return NewAbsenceTypeClient(_m.config).QueryLeaveAllowances(_m)
}

// QueryLeaveRequests queries the "leave_requests" edge of the AbsenceType entity.
func (_m *AbsenceType) QueryLeaveRequests() *LeaveRequestQuery {
	return NewAbsenceTypeClient(_m.config).QueryLeaveRequests(_m)
}

// Update returns a builder for updating this AbsenceType.
// Note that you need to call AbsenceType.Unwrap() before calling this method if this AbsenceType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AbsenceType) Update() *AbsenceTypeUpdateOne {
	return NewAbsenceTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AbsenceType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AbsenceType) Unwrap() *AbsenceType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AbsenceType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AbsenceType) String() string {
	var builder strings.Builder
	builder.WriteString("AbsenceType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("deducts_from_allowance=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeductsFromAllowance))
	builder.WriteString(", ")
	builder.WriteString("requires_approval=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiresApproval))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("requires_signing=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiresSigning))
	builder.WriteString(", ")
	builder.WriteString("signing_template_id=")
	builder.WriteString(_m.SigningTemplateID)
	builder.WriteByte(')')
	return builder.String()
}

// AbsenceTypes is a parsable slice of AbsenceType.
type AbsenceTypes []*AbsenceType
