// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/allowancepool"
)

// AllowancePool is the model entity for the AllowancePool schema.
type AllowancePool struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Pool name (e.g. 'Sick Leave Pool')
	Name string `json:"name,omitempty"`
	// Description
	Description string `json:"description,omitempty"`
	// Hex color for display
	Color string `json:"color,omitempty"`
	// Lucide icon name
	Icon string `json:"icon,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AllowancePoolQuery when eager-loading is set.
	Edges        AllowancePoolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AllowancePoolEdges holds the relations/edges for other nodes in the graph.
type AllowancePoolEdges struct {
	// AbsenceTypes holds the value of the absence_types edge.
	AbsenceTypes []*AbsenceType `json:"absence_types,omitempty"`
	// LeaveAllowances holds the value of the leave_allowances edge.
	LeaveAllowances []*LeaveAllowance `json:"leave_allowances,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AbsenceTypesOrErr returns the AbsenceTypes value or an error if the edge
// was not loaded in eager-loading.
func (e AllowancePoolEdges) AbsenceTypesOrErr() ([]*AbsenceType, error) {
	if e.loadedTypes[0] {
		return e.AbsenceTypes, nil
	}
	return nil, &NotLoadedError{edge: "absence_types"}
}

// LeaveAllowancesOrErr returns the LeaveAllowances value or an error if the edge
// was not loaded in eager-loading.
func (e AllowancePoolEdges) LeaveAllowancesOrErr() ([]*LeaveAllowance, error) {
	if e.loadedTypes[1] {
		return e.LeaveAllowances, nil
	}
	return nil, &NotLoadedError{edge: "leave_allowances"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AllowancePool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case allowancepool.FieldCreateBy, allowancepool.FieldUpdateBy, allowancepool.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case allowancepool.FieldID, allowancepool.FieldName, allowancepool.FieldDescription, allowancepool.FieldColor, allowancepool.FieldIcon:
			values[i] = new(sql.NullString)
		case allowancepool.FieldCreateTime, allowancepool.FieldUpdateTime, allowancepool.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AllowancePool fields.
func (_m *AllowancePool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case allowancepool.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case allowancepool.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case allowancepool.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case allowancepool.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case allowancepool.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case allowancepool.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case allowancepool.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case allowancepool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case allowancepool.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case allowancepool.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case allowancepool.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AllowancePool.
// This includes values selected through modifiers, order, etc.
func (_m *AllowancePool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAbsenceTypes queries the "absence_types" edge of the AllowancePool entity.
func (_m *AllowancePool) QueryAbsenceTypes() *AbsenceTypeQuery {
	return NewAllowancePoolClient(_m.config).QueryAbsenceTypes(_m)
}

// QueryLeaveAllowances queries the "leave_allowances" edge of the AllowancePool entity.
func (_m *AllowancePool) QueryLeaveAllowances() *LeaveAllowanceQuery {
	return NewAllowancePoolClient(_m.config).QueryLeaveAllowances(_m)
}

// Update returns a builder for updating this AllowancePool.
// Note that you need to call AllowancePool.Unwrap() before calling this method if this AllowancePool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AllowancePool) Update() *AllowancePoolUpdateOne {
	return NewAllowancePoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AllowancePool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AllowancePool) Unwrap() *AllowancePool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AllowancePool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AllowancePool) String() string {
	var builder strings.Builder
	builder.WriteString("AllowancePool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteByte(')')
	return builder.String()
}

// AllowancePools is a parsable slice of AllowancePool.
type AllowancePools []*AllowancePool
