// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/go-tangra/go-tangra-hr/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/auditlog"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaveallowance"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaverequest"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AbsenceType is the client for interacting with the AbsenceType builders.
	AbsenceType *AbsenceTypeClient
	// AuditLog is the client for interacting with the AuditLog builders.
	AuditLog *AuditLogClient
	// LeaveAllowance is the client for interacting with the LeaveAllowance builders.
	LeaveAllowance *LeaveAllowanceClient
	// LeaveRequest is the client for interacting with the LeaveRequest builders.
	LeaveRequest *LeaveRequestClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AbsenceType = NewAbsenceTypeClient(c.config)
	c.AuditLog = NewAuditLogClient(c.config)
	c.LeaveAllowance = NewLeaveAllowanceClient(c.config)
	c.LeaveRequest = NewLeaveRequestClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		AbsenceType:    NewAbsenceTypeClient(cfg),
		AuditLog:       NewAuditLogClient(cfg),
		LeaveAllowance: NewLeaveAllowanceClient(cfg),
		LeaveRequest:   NewLeaveRequestClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		AbsenceType:    NewAbsenceTypeClient(cfg),
		AuditLog:       NewAuditLogClient(cfg),
		LeaveAllowance: NewLeaveAllowanceClient(cfg),
		LeaveRequest:   NewLeaveRequestClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AbsenceType.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AbsenceType.Use(hooks...)
	c.AuditLog.Use(hooks...)
	c.LeaveAllowance.Use(hooks...)
	c.LeaveRequest.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AbsenceType.Intercept(interceptors...)
	c.AuditLog.Intercept(interceptors...)
	c.LeaveAllowance.Intercept(interceptors...)
	c.LeaveRequest.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AbsenceTypeMutation:
		return c.AbsenceType.mutate(ctx, m)
	case *AuditLogMutation:
		return c.AuditLog.mutate(ctx, m)
	case *LeaveAllowanceMutation:
		return c.LeaveAllowance.mutate(ctx, m)
	case *LeaveRequestMutation:
		return c.LeaveRequest.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AbsenceTypeClient is a client for the AbsenceType schema.
type AbsenceTypeClient struct {
	config
}

// NewAbsenceTypeClient returns a client for the AbsenceType from the given config.
func NewAbsenceTypeClient(c config) *AbsenceTypeClient {
	return &AbsenceTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `absencetype.Hooks(f(g(h())))`.
func (c *AbsenceTypeClient) Use(hooks ...Hook) {
	c.hooks.AbsenceType = append(c.hooks.AbsenceType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `absencetype.Intercept(f(g(h())))`.
func (c *AbsenceTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.AbsenceType = append(c.inters.AbsenceType, interceptors...)
}

// Create returns a builder for creating a AbsenceType entity.
func (c *AbsenceTypeClient) Create() *AbsenceTypeCreate {
	mutation := newAbsenceTypeMutation(c.config, OpCreate)
	return &AbsenceTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AbsenceType entities.
func (c *AbsenceTypeClient) CreateBulk(builders ...*AbsenceTypeCreate) *AbsenceTypeCreateBulk {
	return &AbsenceTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AbsenceTypeClient) MapCreateBulk(slice any, setFunc func(*AbsenceTypeCreate, int)) *AbsenceTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AbsenceTypeCreateBulk{err: fmt.Errorf("calling to AbsenceTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AbsenceTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AbsenceTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AbsenceType.
func (c *AbsenceTypeClient) Update() *AbsenceTypeUpdate {
	mutation := newAbsenceTypeMutation(c.config, OpUpdate)
	return &AbsenceTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AbsenceTypeClient) UpdateOne(_m *AbsenceType) *AbsenceTypeUpdateOne {
	mutation := newAbsenceTypeMutation(c.config, OpUpdateOne, withAbsenceType(_m))
	return &AbsenceTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AbsenceTypeClient) UpdateOneID(id string) *AbsenceTypeUpdateOne {
	mutation := newAbsenceTypeMutation(c.config, OpUpdateOne, withAbsenceTypeID(id))
	return &AbsenceTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AbsenceType.
func (c *AbsenceTypeClient) Delete() *AbsenceTypeDelete {
	mutation := newAbsenceTypeMutation(c.config, OpDelete)
	return &AbsenceTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AbsenceTypeClient) DeleteOne(_m *AbsenceType) *AbsenceTypeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AbsenceTypeClient) DeleteOneID(id string) *AbsenceTypeDeleteOne {
	builder := c.Delete().Where(absencetype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AbsenceTypeDeleteOne{builder}
}

// Query returns a query builder for AbsenceType.
func (c *AbsenceTypeClient) Query() *AbsenceTypeQuery {
	return &AbsenceTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAbsenceType},
		inters: c.Interceptors(),
	}
}

// Get returns a AbsenceType entity by its id.
func (c *AbsenceTypeClient) Get(ctx context.Context, id string) (*AbsenceType, error) {
	return c.Query().Where(absencetype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AbsenceTypeClient) GetX(ctx context.Context, id string) *AbsenceType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLeaveAllowances queries the leave_allowances edge of a AbsenceType.
func (c *AbsenceTypeClient) QueryLeaveAllowances(_m *AbsenceType) *LeaveAllowanceQuery {
	query := (&LeaveAllowanceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(absencetype.Table, absencetype.FieldID, id),
			sqlgraph.To(leaveallowance.Table, leaveallowance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, absencetype.LeaveAllowancesTable, absencetype.LeaveAllowancesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLeaveRequests queries the leave_requests edge of a AbsenceType.
func (c *AbsenceTypeClient) QueryLeaveRequests(_m *AbsenceType) *LeaveRequestQuery {
	query := (&LeaveRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(absencetype.Table, absencetype.FieldID, id),
			sqlgraph.To(leaverequest.Table, leaverequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, absencetype.LeaveRequestsTable, absencetype.LeaveRequestsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AbsenceTypeClient) Hooks() []Hook {
	hooks := c.hooks.AbsenceType
	return append(hooks[:len(hooks):len(hooks)], absencetype.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *AbsenceTypeClient) Interceptors() []Interceptor {
	return c.inters.AbsenceType
}

func (c *AbsenceTypeClient) mutate(ctx context.Context, m *AbsenceTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AbsenceTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AbsenceTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AbsenceTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AbsenceTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AbsenceType mutation op: %q", m.Op())
	}
}

// AuditLogClient is a client for the AuditLog schema.
type AuditLogClient struct {
	config
}

// NewAuditLogClient returns a client for the AuditLog from the given config.
func NewAuditLogClient(c config) *AuditLogClient {
	return &AuditLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditlog.Hooks(f(g(h())))`.
func (c *AuditLogClient) Use(hooks ...Hook) {
	c.hooks.AuditLog = append(c.hooks.AuditLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditlog.Intercept(f(g(h())))`.
func (c *AuditLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditLog = append(c.inters.AuditLog, interceptors...)
}

// Create returns a builder for creating a AuditLog entity.
func (c *AuditLogClient) Create() *AuditLogCreate {
	mutation := newAuditLogMutation(c.config, OpCreate)
	return &AuditLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditLog entities.
func (c *AuditLogClient) CreateBulk(builders ...*AuditLogCreate) *AuditLogCreateBulk {
	return &AuditLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditLogClient) MapCreateBulk(slice any, setFunc func(*AuditLogCreate, int)) *AuditLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditLogCreateBulk{err: fmt.Errorf("calling to AuditLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditLog.
func (c *AuditLogClient) Update() *AuditLogUpdate {
	mutation := newAuditLogMutation(c.config, OpUpdate)
	return &AuditLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditLogClient) UpdateOne(_m *AuditLog) *AuditLogUpdateOne {
	mutation := newAuditLogMutation(c.config, OpUpdateOne, withAuditLog(_m))
	return &AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditLogClient) UpdateOneID(id uint32) *AuditLogUpdateOne {
	mutation := newAuditLogMutation(c.config, OpUpdateOne, withAuditLogID(id))
	return &AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditLog.
func (c *AuditLogClient) Delete() *AuditLogDelete {
	mutation := newAuditLogMutation(c.config, OpDelete)
	return &AuditLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditLogClient) DeleteOne(_m *AuditLog) *AuditLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditLogClient) DeleteOneID(id uint32) *AuditLogDeleteOne {
	builder := c.Delete().Where(auditlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditLogDeleteOne{builder}
}

// Query returns a query builder for AuditLog.
func (c *AuditLogClient) Query() *AuditLogQuery {
	return &AuditLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditLog},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditLog entity by its id.
func (c *AuditLogClient) Get(ctx context.Context, id uint32) (*AuditLog, error) {
	return c.Query().Where(auditlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditLogClient) GetX(ctx context.Context, id uint32) *AuditLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditLogClient) Hooks() []Hook {
	hooks := c.hooks.AuditLog
	return append(hooks[:len(hooks):len(hooks)], auditlog.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *AuditLogClient) Interceptors() []Interceptor {
	return c.inters.AuditLog
}

func (c *AuditLogClient) mutate(ctx context.Context, m *AuditLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditLog mutation op: %q", m.Op())
	}
}

// LeaveAllowanceClient is a client for the LeaveAllowance schema.
type LeaveAllowanceClient struct {
	config
}

// NewLeaveAllowanceClient returns a client for the LeaveAllowance from the given config.
func NewLeaveAllowanceClient(c config) *LeaveAllowanceClient {
	return &LeaveAllowanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `leaveallowance.Hooks(f(g(h())))`.
func (c *LeaveAllowanceClient) Use(hooks ...Hook) {
	c.hooks.LeaveAllowance = append(c.hooks.LeaveAllowance, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `leaveallowance.Intercept(f(g(h())))`.
func (c *LeaveAllowanceClient) Intercept(interceptors ...Interceptor) {
	c.inters.LeaveAllowance = append(c.inters.LeaveAllowance, interceptors...)
}

// Create returns a builder for creating a LeaveAllowance entity.
func (c *LeaveAllowanceClient) Create() *LeaveAllowanceCreate {
	mutation := newLeaveAllowanceMutation(c.config, OpCreate)
	return &LeaveAllowanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LeaveAllowance entities.
func (c *LeaveAllowanceClient) CreateBulk(builders ...*LeaveAllowanceCreate) *LeaveAllowanceCreateBulk {
	return &LeaveAllowanceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LeaveAllowanceClient) MapCreateBulk(slice any, setFunc func(*LeaveAllowanceCreate, int)) *LeaveAllowanceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LeaveAllowanceCreateBulk{err: fmt.Errorf("calling to LeaveAllowanceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LeaveAllowanceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LeaveAllowanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LeaveAllowance.
func (c *LeaveAllowanceClient) Update() *LeaveAllowanceUpdate {
	mutation := newLeaveAllowanceMutation(c.config, OpUpdate)
	return &LeaveAllowanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LeaveAllowanceClient) UpdateOne(_m *LeaveAllowance) *LeaveAllowanceUpdateOne {
	mutation := newLeaveAllowanceMutation(c.config, OpUpdateOne, withLeaveAllowance(_m))
	return &LeaveAllowanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LeaveAllowanceClient) UpdateOneID(id string) *LeaveAllowanceUpdateOne {
	mutation := newLeaveAllowanceMutation(c.config, OpUpdateOne, withLeaveAllowanceID(id))
	return &LeaveAllowanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LeaveAllowance.
func (c *LeaveAllowanceClient) Delete() *LeaveAllowanceDelete {
	mutation := newLeaveAllowanceMutation(c.config, OpDelete)
	return &LeaveAllowanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LeaveAllowanceClient) DeleteOne(_m *LeaveAllowance) *LeaveAllowanceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LeaveAllowanceClient) DeleteOneID(id string) *LeaveAllowanceDeleteOne {
	builder := c.Delete().Where(leaveallowance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LeaveAllowanceDeleteOne{builder}
}

// Query returns a query builder for LeaveAllowance.
func (c *LeaveAllowanceClient) Query() *LeaveAllowanceQuery {
	return &LeaveAllowanceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLeaveAllowance},
		inters: c.Interceptors(),
	}
}

// Get returns a LeaveAllowance entity by its id.
func (c *LeaveAllowanceClient) Get(ctx context.Context, id string) (*LeaveAllowance, error) {
	return c.Query().Where(leaveallowance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LeaveAllowanceClient) GetX(ctx context.Context, id string) *LeaveAllowance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAbsenceType queries the absence_type edge of a LeaveAllowance.
func (c *LeaveAllowanceClient) QueryAbsenceType(_m *LeaveAllowance) *AbsenceTypeQuery {
	query := (&AbsenceTypeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(leaveallowance.Table, leaveallowance.FieldID, id),
			sqlgraph.To(absencetype.Table, absencetype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, leaveallowance.AbsenceTypeTable, leaveallowance.AbsenceTypeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LeaveAllowanceClient) Hooks() []Hook {
	hooks := c.hooks.LeaveAllowance
	return append(hooks[:len(hooks):len(hooks)], leaveallowance.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *LeaveAllowanceClient) Interceptors() []Interceptor {
	return c.inters.LeaveAllowance
}

func (c *LeaveAllowanceClient) mutate(ctx context.Context, m *LeaveAllowanceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LeaveAllowanceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LeaveAllowanceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LeaveAllowanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LeaveAllowanceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LeaveAllowance mutation op: %q", m.Op())
	}
}

// LeaveRequestClient is a client for the LeaveRequest schema.
type LeaveRequestClient struct {
	config
}

// NewLeaveRequestClient returns a client for the LeaveRequest from the given config.
func NewLeaveRequestClient(c config) *LeaveRequestClient {
	return &LeaveRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `leaverequest.Hooks(f(g(h())))`.
func (c *LeaveRequestClient) Use(hooks ...Hook) {
	c.hooks.LeaveRequest = append(c.hooks.LeaveRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `leaverequest.Intercept(f(g(h())))`.
func (c *LeaveRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.LeaveRequest = append(c.inters.LeaveRequest, interceptors...)
}

// Create returns a builder for creating a LeaveRequest entity.
func (c *LeaveRequestClient) Create() *LeaveRequestCreate {
	mutation := newLeaveRequestMutation(c.config, OpCreate)
	return &LeaveRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LeaveRequest entities.
func (c *LeaveRequestClient) CreateBulk(builders ...*LeaveRequestCreate) *LeaveRequestCreateBulk {
	return &LeaveRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LeaveRequestClient) MapCreateBulk(slice any, setFunc func(*LeaveRequestCreate, int)) *LeaveRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LeaveRequestCreateBulk{err: fmt.Errorf("calling to LeaveRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LeaveRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LeaveRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LeaveRequest.
func (c *LeaveRequestClient) Update() *LeaveRequestUpdate {
	mutation := newLeaveRequestMutation(c.config, OpUpdate)
	return &LeaveRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LeaveRequestClient) UpdateOne(_m *LeaveRequest) *LeaveRequestUpdateOne {
	mutation := newLeaveRequestMutation(c.config, OpUpdateOne, withLeaveRequest(_m))
	return &LeaveRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LeaveRequestClient) UpdateOneID(id string) *LeaveRequestUpdateOne {
	mutation := newLeaveRequestMutation(c.config, OpUpdateOne, withLeaveRequestID(id))
	return &LeaveRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LeaveRequest.
func (c *LeaveRequestClient) Delete() *LeaveRequestDelete {
	mutation := newLeaveRequestMutation(c.config, OpDelete)
	return &LeaveRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LeaveRequestClient) DeleteOne(_m *LeaveRequest) *LeaveRequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LeaveRequestClient) DeleteOneID(id string) *LeaveRequestDeleteOne {
	builder := c.Delete().Where(leaverequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LeaveRequestDeleteOne{builder}
}

// Query returns a query builder for LeaveRequest.
func (c *LeaveRequestClient) Query() *LeaveRequestQuery {
	return &LeaveRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLeaveRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a LeaveRequest entity by its id.
func (c *LeaveRequestClient) Get(ctx context.Context, id string) (*LeaveRequest, error) {
	return c.Query().Where(leaverequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LeaveRequestClient) GetX(ctx context.Context, id string) *LeaveRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAbsenceType queries the absence_type edge of a LeaveRequest.
func (c *LeaveRequestClient) QueryAbsenceType(_m *LeaveRequest) *AbsenceTypeQuery {
	query := (&AbsenceTypeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(leaverequest.Table, leaverequest.FieldID, id),
			sqlgraph.To(absencetype.Table, absencetype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, leaverequest.AbsenceTypeTable, leaverequest.AbsenceTypeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LeaveRequestClient) Hooks() []Hook {
	hooks := c.hooks.LeaveRequest
	return append(hooks[:len(hooks):len(hooks)], leaverequest.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *LeaveRequestClient) Interceptors() []Interceptor {
	return c.inters.LeaveRequest
}

func (c *LeaveRequestClient) mutate(ctx context.Context, m *LeaveRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LeaveRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LeaveRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LeaveRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LeaveRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LeaveRequest mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AbsenceType, AuditLog, LeaveAllowance, LeaveRequest []ent.Hook
	}
	inters struct {
		AbsenceType, AuditLog, LeaveAllowance, LeaveRequest []ent.Interceptor
	}
)
