// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/auditlog"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaveallowance"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaverequest"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 4)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   absencetype.Table,
			Columns: absencetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: absencetype.FieldID,
			},
		},
		Type: "AbsenceType",
		Fields: map[string]*sqlgraph.FieldSpec{
			absencetype.FieldCreateBy:             {Type: field.TypeUint32, Column: absencetype.FieldCreateBy},
			absencetype.FieldUpdateBy:             {Type: field.TypeUint32, Column: absencetype.FieldUpdateBy},
			absencetype.FieldCreateTime:           {Type: field.TypeTime, Column: absencetype.FieldCreateTime},
			absencetype.FieldUpdateTime:           {Type: field.TypeTime, Column: absencetype.FieldUpdateTime},
			absencetype.FieldDeleteTime:           {Type: field.TypeTime, Column: absencetype.FieldDeleteTime},
			absencetype.FieldTenantID:             {Type: field.TypeUint32, Column: absencetype.FieldTenantID},
			absencetype.FieldName:                 {Type: field.TypeString, Column: absencetype.FieldName},
			absencetype.FieldDescription:          {Type: field.TypeString, Column: absencetype.FieldDescription},
			absencetype.FieldColor:                {Type: field.TypeString, Column: absencetype.FieldColor},
			absencetype.FieldIcon:                 {Type: field.TypeString, Column: absencetype.FieldIcon},
			absencetype.FieldDeductsFromAllowance: {Type: field.TypeBool, Column: absencetype.FieldDeductsFromAllowance},
			absencetype.FieldRequiresApproval:     {Type: field.TypeBool, Column: absencetype.FieldRequiresApproval},
			absencetype.FieldIsActive:             {Type: field.TypeBool, Column: absencetype.FieldIsActive},
			absencetype.FieldSortOrder:            {Type: field.TypeInt, Column: absencetype.FieldSortOrder},
			absencetype.FieldMetadata:             {Type: field.TypeJSON, Column: absencetype.FieldMetadata},
			absencetype.FieldRequiresSigning:      {Type: field.TypeBool, Column: absencetype.FieldRequiresSigning},
			absencetype.FieldSigningTemplateID:    {Type: field.TypeString, Column: absencetype.FieldSigningTemplateID},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   auditlog.Table,
			Columns: auditlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: auditlog.FieldID,
			},
		},
		Type: "AuditLog",
		Fields: map[string]*sqlgraph.FieldSpec{
			auditlog.FieldCreateTime:         {Type: field.TypeTime, Column: auditlog.FieldCreateTime},
			auditlog.FieldUpdateTime:         {Type: field.TypeTime, Column: auditlog.FieldUpdateTime},
			auditlog.FieldDeleteTime:         {Type: field.TypeTime, Column: auditlog.FieldDeleteTime},
			auditlog.FieldTenantID:           {Type: field.TypeUint32, Column: auditlog.FieldTenantID},
			auditlog.FieldAuditID:            {Type: field.TypeString, Column: auditlog.FieldAuditID},
			auditlog.FieldRequestID:          {Type: field.TypeString, Column: auditlog.FieldRequestID},
			auditlog.FieldOperation:          {Type: field.TypeString, Column: auditlog.FieldOperation},
			auditlog.FieldServiceName:        {Type: field.TypeString, Column: auditlog.FieldServiceName},
			auditlog.FieldClientID:           {Type: field.TypeString, Column: auditlog.FieldClientID},
			auditlog.FieldClientCommonName:   {Type: field.TypeString, Column: auditlog.FieldClientCommonName},
			auditlog.FieldClientOrganization: {Type: field.TypeString, Column: auditlog.FieldClientOrganization},
			auditlog.FieldClientSerialNumber: {Type: field.TypeString, Column: auditlog.FieldClientSerialNumber},
			auditlog.FieldIsAuthenticated:    {Type: field.TypeBool, Column: auditlog.FieldIsAuthenticated},
			auditlog.FieldSuccess:            {Type: field.TypeBool, Column: auditlog.FieldSuccess},
			auditlog.FieldErrorCode:          {Type: field.TypeInt32, Column: auditlog.FieldErrorCode},
			auditlog.FieldErrorMessage:       {Type: field.TypeString, Column: auditlog.FieldErrorMessage},
			auditlog.FieldLatencyMs:          {Type: field.TypeInt64, Column: auditlog.FieldLatencyMs},
			auditlog.FieldPeerAddress:        {Type: field.TypeString, Column: auditlog.FieldPeerAddress},
			auditlog.FieldGeoLocation:        {Type: field.TypeJSON, Column: auditlog.FieldGeoLocation},
			auditlog.FieldLogHash:            {Type: field.TypeString, Column: auditlog.FieldLogHash},
			auditlog.FieldSignature:          {Type: field.TypeBytes, Column: auditlog.FieldSignature},
			auditlog.FieldMetadata:           {Type: field.TypeJSON, Column: auditlog.FieldMetadata},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   leaveallowance.Table,
			Columns: leaveallowance.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: leaveallowance.FieldID,
			},
		},
		Type: "LeaveAllowance",
		Fields: map[string]*sqlgraph.FieldSpec{
			leaveallowance.FieldCreateBy:      {Type: field.TypeUint32, Column: leaveallowance.FieldCreateBy},
			leaveallowance.FieldUpdateBy:      {Type: field.TypeUint32, Column: leaveallowance.FieldUpdateBy},
			leaveallowance.FieldCreateTime:    {Type: field.TypeTime, Column: leaveallowance.FieldCreateTime},
			leaveallowance.FieldUpdateTime:    {Type: field.TypeTime, Column: leaveallowance.FieldUpdateTime},
			leaveallowance.FieldDeleteTime:    {Type: field.TypeTime, Column: leaveallowance.FieldDeleteTime},
			leaveallowance.FieldTenantID:      {Type: field.TypeUint32, Column: leaveallowance.FieldTenantID},
			leaveallowance.FieldUserID:        {Type: field.TypeUint32, Column: leaveallowance.FieldUserID},
			leaveallowance.FieldUserName:      {Type: field.TypeString, Column: leaveallowance.FieldUserName},
			leaveallowance.FieldAbsenceTypeID: {Type: field.TypeString, Column: leaveallowance.FieldAbsenceTypeID},
			leaveallowance.FieldYear:          {Type: field.TypeInt, Column: leaveallowance.FieldYear},
			leaveallowance.FieldTotalDays:     {Type: field.TypeFloat64, Column: leaveallowance.FieldTotalDays},
			leaveallowance.FieldUsedDays:      {Type: field.TypeFloat64, Column: leaveallowance.FieldUsedDays},
			leaveallowance.FieldCarriedOver:   {Type: field.TypeFloat64, Column: leaveallowance.FieldCarriedOver},
			leaveallowance.FieldNotes:         {Type: field.TypeString, Column: leaveallowance.FieldNotes},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   leaverequest.Table,
			Columns: leaverequest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: leaverequest.FieldID,
			},
		},
		Type: "LeaveRequest",
		Fields: map[string]*sqlgraph.FieldSpec{
			leaverequest.FieldCreateBy:         {Type: field.TypeUint32, Column: leaverequest.FieldCreateBy},
			leaverequest.FieldUpdateBy:         {Type: field.TypeUint32, Column: leaverequest.FieldUpdateBy},
			leaverequest.FieldCreateTime:       {Type: field.TypeTime, Column: leaverequest.FieldCreateTime},
			leaverequest.FieldUpdateTime:       {Type: field.TypeTime, Column: leaverequest.FieldUpdateTime},
			leaverequest.FieldDeleteTime:       {Type: field.TypeTime, Column: leaverequest.FieldDeleteTime},
			leaverequest.FieldTenantID:         {Type: field.TypeUint32, Column: leaverequest.FieldTenantID},
			leaverequest.FieldUserID:           {Type: field.TypeUint32, Column: leaverequest.FieldUserID},
			leaverequest.FieldUserName:         {Type: field.TypeString, Column: leaverequest.FieldUserName},
			leaverequest.FieldUserEmail:        {Type: field.TypeString, Column: leaverequest.FieldUserEmail},
			leaverequest.FieldOrgUnitName:      {Type: field.TypeString, Column: leaverequest.FieldOrgUnitName},
			leaverequest.FieldAbsenceTypeID:    {Type: field.TypeString, Column: leaverequest.FieldAbsenceTypeID},
			leaverequest.FieldStartDate:        {Type: field.TypeTime, Column: leaverequest.FieldStartDate},
			leaverequest.FieldEndDate:          {Type: field.TypeTime, Column: leaverequest.FieldEndDate},
			leaverequest.FieldDays:             {Type: field.TypeFloat64, Column: leaverequest.FieldDays},
			leaverequest.FieldStatus:           {Type: field.TypeEnum, Column: leaverequest.FieldStatus},
			leaverequest.FieldSigningRequestID: {Type: field.TypeString, Column: leaverequest.FieldSigningRequestID},
			leaverequest.FieldReason:           {Type: field.TypeString, Column: leaverequest.FieldReason},
			leaverequest.FieldReviewNotes:      {Type: field.TypeString, Column: leaverequest.FieldReviewNotes},
			leaverequest.FieldReviewedBy:       {Type: field.TypeUint32, Column: leaverequest.FieldReviewedBy},
			leaverequest.FieldReviewerName:     {Type: field.TypeString, Column: leaverequest.FieldReviewerName},
			leaverequest.FieldReviewedAt:       {Type: field.TypeTime, Column: leaverequest.FieldReviewedAt},
			leaverequest.FieldNotes:            {Type: field.TypeString, Column: leaverequest.FieldNotes},
			leaverequest.FieldMetadata:         {Type: field.TypeJSON, Column: leaverequest.FieldMetadata},
		},
	}
	graph.MustAddE(
		"leave_allowances",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveAllowancesTable,
			Columns: []string{absencetype.LeaveAllowancesColumn},
			Bidi:    false,
		},
		"AbsenceType",
		"LeaveAllowance",
	)
	graph.MustAddE(
		"leave_requests",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   absencetype.LeaveRequestsTable,
			Columns: []string{absencetype.LeaveRequestsColumn},
			Bidi:    false,
		},
		"AbsenceType",
		"LeaveRequest",
	)
	graph.MustAddE(
		"absence_type",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaveallowance.AbsenceTypeTable,
			Columns: []string{leaveallowance.AbsenceTypeColumn},
			Bidi:    false,
		},
		"LeaveAllowance",
		"AbsenceType",
	)
	graph.MustAddE(
		"absence_type",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaverequest.AbsenceTypeTable,
			Columns: []string{leaverequest.AbsenceTypeColumn},
			Bidi:    false,
		},
		"LeaveRequest",
		"AbsenceType",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *AbsenceTypeQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AbsenceTypeQuery builder.
func (_q *AbsenceTypeQuery) Filter() *AbsenceTypeFilter {
	return &AbsenceTypeFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *AbsenceTypeMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AbsenceTypeMutation builder.
func (m *AbsenceTypeMutation) Filter() *AbsenceTypeFilter {
	return &AbsenceTypeFilter{config: m.config, predicateAdder: m}
}

// AbsenceTypeFilter provides a generic filtering capability at runtime for AbsenceTypeQuery.
type AbsenceTypeFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AbsenceTypeFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *AbsenceTypeFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(absencetype.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *AbsenceTypeFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(absencetype.FieldCreateBy))
}

// WhereUpdateBy applies the entql uint32 predicate on the update_by field.
func (f *AbsenceTypeFilter) WhereUpdateBy(p entql.Uint32P) {
	f.Where(p.Field(absencetype.FieldUpdateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *AbsenceTypeFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(absencetype.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *AbsenceTypeFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(absencetype.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *AbsenceTypeFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(absencetype.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *AbsenceTypeFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(absencetype.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *AbsenceTypeFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(absencetype.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *AbsenceTypeFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(absencetype.FieldDescription))
}

// WhereColor applies the entql string predicate on the color field.
func (f *AbsenceTypeFilter) WhereColor(p entql.StringP) {
	f.Where(p.Field(absencetype.FieldColor))
}

// WhereIcon applies the entql string predicate on the icon field.
func (f *AbsenceTypeFilter) WhereIcon(p entql.StringP) {
	f.Where(p.Field(absencetype.FieldIcon))
}

// WhereDeductsFromAllowance applies the entql bool predicate on the deducts_from_allowance field.
func (f *AbsenceTypeFilter) WhereDeductsFromAllowance(p entql.BoolP) {
	f.Where(p.Field(absencetype.FieldDeductsFromAllowance))
}

// WhereRequiresApproval applies the entql bool predicate on the requires_approval field.
func (f *AbsenceTypeFilter) WhereRequiresApproval(p entql.BoolP) {
	f.Where(p.Field(absencetype.FieldRequiresApproval))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *AbsenceTypeFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(absencetype.FieldIsActive))
}

// WhereSortOrder applies the entql int predicate on the sort_order field.
func (f *AbsenceTypeFilter) WhereSortOrder(p entql.IntP) {
	f.Where(p.Field(absencetype.FieldSortOrder))
}

// WhereMetadata applies the entql json.RawMessage predicate on the metadata field.
func (f *AbsenceTypeFilter) WhereMetadata(p entql.BytesP) {
	f.Where(p.Field(absencetype.FieldMetadata))
}

// WhereRequiresSigning applies the entql bool predicate on the requires_signing field.
func (f *AbsenceTypeFilter) WhereRequiresSigning(p entql.BoolP) {
	f.Where(p.Field(absencetype.FieldRequiresSigning))
}

// WhereSigningTemplateID applies the entql string predicate on the signing_template_id field.
func (f *AbsenceTypeFilter) WhereSigningTemplateID(p entql.StringP) {
	f.Where(p.Field(absencetype.FieldSigningTemplateID))
}

// WhereHasLeaveAllowances applies a predicate to check if query has an edge leave_allowances.
func (f *AbsenceTypeFilter) WhereHasLeaveAllowances() {
	f.Where(entql.HasEdge("leave_allowances"))
}

// WhereHasLeaveAllowancesWith applies a predicate to check if query has an edge leave_allowances with a given conditions (other predicates).
func (f *AbsenceTypeFilter) WhereHasLeaveAllowancesWith(preds ...predicate.LeaveAllowance) {
	f.Where(entql.HasEdgeWith("leave_allowances", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasLeaveRequests applies a predicate to check if query has an edge leave_requests.
func (f *AbsenceTypeFilter) WhereHasLeaveRequests() {
	f.Where(entql.HasEdge("leave_requests"))
}

// WhereHasLeaveRequestsWith applies a predicate to check if query has an edge leave_requests with a given conditions (other predicates).
func (f *AbsenceTypeFilter) WhereHasLeaveRequestsWith(preds ...predicate.LeaveRequest) {
	f.Where(entql.HasEdgeWith("leave_requests", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *AuditLogQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AuditLogQuery builder.
func (_q *AuditLogQuery) Filter() *AuditLogFilter {
	return &AuditLogFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *AuditLogMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AuditLogMutation builder.
func (m *AuditLogMutation) Filter() *AuditLogFilter {
	return &AuditLogFilter{config: m.config, predicateAdder: m}
}

// AuditLogFilter provides a generic filtering capability at runtime for AuditLogQuery.
type AuditLogFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AuditLogFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *AuditLogFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(auditlog.FieldID))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *AuditLogFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(auditlog.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *AuditLogFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(auditlog.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *AuditLogFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(auditlog.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *AuditLogFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(auditlog.FieldTenantID))
}

// WhereAuditID applies the entql string predicate on the audit_id field.
func (f *AuditLogFilter) WhereAuditID(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldAuditID))
}

// WhereRequestID applies the entql string predicate on the request_id field.
func (f *AuditLogFilter) WhereRequestID(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldRequestID))
}

// WhereOperation applies the entql string predicate on the operation field.
func (f *AuditLogFilter) WhereOperation(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldOperation))
}

// WhereServiceName applies the entql string predicate on the service_name field.
func (f *AuditLogFilter) WhereServiceName(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldServiceName))
}

// WhereClientID applies the entql string predicate on the client_id field.
func (f *AuditLogFilter) WhereClientID(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientID))
}

// WhereClientCommonName applies the entql string predicate on the client_common_name field.
func (f *AuditLogFilter) WhereClientCommonName(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientCommonName))
}

// WhereClientOrganization applies the entql string predicate on the client_organization field.
func (f *AuditLogFilter) WhereClientOrganization(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientOrganization))
}

// WhereClientSerialNumber applies the entql string predicate on the client_serial_number field.
func (f *AuditLogFilter) WhereClientSerialNumber(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientSerialNumber))
}

// WhereIsAuthenticated applies the entql bool predicate on the is_authenticated field.
func (f *AuditLogFilter) WhereIsAuthenticated(p entql.BoolP) {
	f.Where(p.Field(auditlog.FieldIsAuthenticated))
}

// WhereSuccess applies the entql bool predicate on the success field.
func (f *AuditLogFilter) WhereSuccess(p entql.BoolP) {
	f.Where(p.Field(auditlog.FieldSuccess))
}

// WhereErrorCode applies the entql int32 predicate on the error_code field.
func (f *AuditLogFilter) WhereErrorCode(p entql.Int32P) {
	f.Where(p.Field(auditlog.FieldErrorCode))
}

// WhereErrorMessage applies the entql string predicate on the error_message field.
func (f *AuditLogFilter) WhereErrorMessage(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldErrorMessage))
}

// WhereLatencyMs applies the entql int64 predicate on the latency_ms field.
func (f *AuditLogFilter) WhereLatencyMs(p entql.Int64P) {
	f.Where(p.Field(auditlog.FieldLatencyMs))
}

// WherePeerAddress applies the entql string predicate on the peer_address field.
func (f *AuditLogFilter) WherePeerAddress(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldPeerAddress))
}

// WhereGeoLocation applies the entql json.RawMessage predicate on the geo_location field.
func (f *AuditLogFilter) WhereGeoLocation(p entql.BytesP) {
	f.Where(p.Field(auditlog.FieldGeoLocation))
}

// WhereLogHash applies the entql string predicate on the log_hash field.
func (f *AuditLogFilter) WhereLogHash(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldLogHash))
}

// WhereSignature applies the entql []byte predicate on the signature field.
func (f *AuditLogFilter) WhereSignature(p entql.BytesP) {
	f.Where(p.Field(auditlog.FieldSignature))
}

// WhereMetadata applies the entql json.RawMessage predicate on the metadata field.
func (f *AuditLogFilter) WhereMetadata(p entql.BytesP) {
	f.Where(p.Field(auditlog.FieldMetadata))
}

// addPredicate implements the predicateAdder interface.
func (_q *LeaveAllowanceQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the LeaveAllowanceQuery builder.
func (_q *LeaveAllowanceQuery) Filter() *LeaveAllowanceFilter {
	return &LeaveAllowanceFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *LeaveAllowanceMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the LeaveAllowanceMutation builder.
func (m *LeaveAllowanceMutation) Filter() *LeaveAllowanceFilter {
	return &LeaveAllowanceFilter{config: m.config, predicateAdder: m}
}

// LeaveAllowanceFilter provides a generic filtering capability at runtime for LeaveAllowanceQuery.
type LeaveAllowanceFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *LeaveAllowanceFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *LeaveAllowanceFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(leaveallowance.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *LeaveAllowanceFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(leaveallowance.FieldCreateBy))
}

// WhereUpdateBy applies the entql uint32 predicate on the update_by field.
func (f *LeaveAllowanceFilter) WhereUpdateBy(p entql.Uint32P) {
	f.Where(p.Field(leaveallowance.FieldUpdateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *LeaveAllowanceFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(leaveallowance.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *LeaveAllowanceFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(leaveallowance.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *LeaveAllowanceFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(leaveallowance.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *LeaveAllowanceFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(leaveallowance.FieldTenantID))
}

// WhereUserID applies the entql uint32 predicate on the user_id field.
func (f *LeaveAllowanceFilter) WhereUserID(p entql.Uint32P) {
	f.Where(p.Field(leaveallowance.FieldUserID))
}

// WhereUserName applies the entql string predicate on the user_name field.
func (f *LeaveAllowanceFilter) WhereUserName(p entql.StringP) {
	f.Where(p.Field(leaveallowance.FieldUserName))
}

// WhereAbsenceTypeID applies the entql string predicate on the absence_type_id field.
func (f *LeaveAllowanceFilter) WhereAbsenceTypeID(p entql.StringP) {
	f.Where(p.Field(leaveallowance.FieldAbsenceTypeID))
}

// WhereYear applies the entql int predicate on the year field.
func (f *LeaveAllowanceFilter) WhereYear(p entql.IntP) {
	f.Where(p.Field(leaveallowance.FieldYear))
}

// WhereTotalDays applies the entql float64 predicate on the total_days field.
func (f *LeaveAllowanceFilter) WhereTotalDays(p entql.Float64P) {
	f.Where(p.Field(leaveallowance.FieldTotalDays))
}

// WhereUsedDays applies the entql float64 predicate on the used_days field.
func (f *LeaveAllowanceFilter) WhereUsedDays(p entql.Float64P) {
	f.Where(p.Field(leaveallowance.FieldUsedDays))
}

// WhereCarriedOver applies the entql float64 predicate on the carried_over field.
func (f *LeaveAllowanceFilter) WhereCarriedOver(p entql.Float64P) {
	f.Where(p.Field(leaveallowance.FieldCarriedOver))
}

// WhereNotes applies the entql string predicate on the notes field.
func (f *LeaveAllowanceFilter) WhereNotes(p entql.StringP) {
	f.Where(p.Field(leaveallowance.FieldNotes))
}

// WhereHasAbsenceType applies a predicate to check if query has an edge absence_type.
func (f *LeaveAllowanceFilter) WhereHasAbsenceType() {
	f.Where(entql.HasEdge("absence_type"))
}

// WhereHasAbsenceTypeWith applies a predicate to check if query has an edge absence_type with a given conditions (other predicates).
func (f *LeaveAllowanceFilter) WhereHasAbsenceTypeWith(preds ...predicate.AbsenceType) {
	f.Where(entql.HasEdgeWith("absence_type", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *LeaveRequestQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the LeaveRequestQuery builder.
func (_q *LeaveRequestQuery) Filter() *LeaveRequestFilter {
	return &LeaveRequestFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *LeaveRequestMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the LeaveRequestMutation builder.
func (m *LeaveRequestMutation) Filter() *LeaveRequestFilter {
	return &LeaveRequestFilter{config: m.config, predicateAdder: m}
}

// LeaveRequestFilter provides a generic filtering capability at runtime for LeaveRequestQuery.
type LeaveRequestFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *LeaveRequestFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *LeaveRequestFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *LeaveRequestFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(leaverequest.FieldCreateBy))
}

// WhereUpdateBy applies the entql uint32 predicate on the update_by field.
func (f *LeaveRequestFilter) WhereUpdateBy(p entql.Uint32P) {
	f.Where(p.Field(leaverequest.FieldUpdateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *LeaveRequestFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(leaverequest.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *LeaveRequestFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(leaverequest.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *LeaveRequestFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(leaverequest.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *LeaveRequestFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(leaverequest.FieldTenantID))
}

// WhereUserID applies the entql uint32 predicate on the user_id field.
func (f *LeaveRequestFilter) WhereUserID(p entql.Uint32P) {
	f.Where(p.Field(leaverequest.FieldUserID))
}

// WhereUserName applies the entql string predicate on the user_name field.
func (f *LeaveRequestFilter) WhereUserName(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldUserName))
}

// WhereUserEmail applies the entql string predicate on the user_email field.
func (f *LeaveRequestFilter) WhereUserEmail(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldUserEmail))
}

// WhereOrgUnitName applies the entql string predicate on the org_unit_name field.
func (f *LeaveRequestFilter) WhereOrgUnitName(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldOrgUnitName))
}

// WhereAbsenceTypeID applies the entql string predicate on the absence_type_id field.
func (f *LeaveRequestFilter) WhereAbsenceTypeID(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldAbsenceTypeID))
}

// WhereStartDate applies the entql time.Time predicate on the start_date field.
func (f *LeaveRequestFilter) WhereStartDate(p entql.TimeP) {
	f.Where(p.Field(leaverequest.FieldStartDate))
}

// WhereEndDate applies the entql time.Time predicate on the end_date field.
func (f *LeaveRequestFilter) WhereEndDate(p entql.TimeP) {
	f.Where(p.Field(leaverequest.FieldEndDate))
}

// WhereDays applies the entql float64 predicate on the days field.
func (f *LeaveRequestFilter) WhereDays(p entql.Float64P) {
	f.Where(p.Field(leaverequest.FieldDays))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *LeaveRequestFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldStatus))
}

// WhereSigningRequestID applies the entql string predicate on the signing_request_id field.
func (f *LeaveRequestFilter) WhereSigningRequestID(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldSigningRequestID))
}

// WhereReason applies the entql string predicate on the reason field.
func (f *LeaveRequestFilter) WhereReason(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldReason))
}

// WhereReviewNotes applies the entql string predicate on the review_notes field.
func (f *LeaveRequestFilter) WhereReviewNotes(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldReviewNotes))
}

// WhereReviewedBy applies the entql uint32 predicate on the reviewed_by field.
func (f *LeaveRequestFilter) WhereReviewedBy(p entql.Uint32P) {
	f.Where(p.Field(leaverequest.FieldReviewedBy))
}

// WhereReviewerName applies the entql string predicate on the reviewer_name field.
func (f *LeaveRequestFilter) WhereReviewerName(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldReviewerName))
}

// WhereReviewedAt applies the entql time.Time predicate on the reviewed_at field.
func (f *LeaveRequestFilter) WhereReviewedAt(p entql.TimeP) {
	f.Where(p.Field(leaverequest.FieldReviewedAt))
}

// WhereNotes applies the entql string predicate on the notes field.
func (f *LeaveRequestFilter) WhereNotes(p entql.StringP) {
	f.Where(p.Field(leaverequest.FieldNotes))
}

// WhereMetadata applies the entql json.RawMessage predicate on the metadata field.
func (f *LeaveRequestFilter) WhereMetadata(p entql.BytesP) {
	f.Where(p.Field(leaverequest.FieldMetadata))
}

// WhereHasAbsenceType applies a predicate to check if query has an edge absence_type.
func (f *LeaveRequestFilter) WhereHasAbsenceType() {
	f.Where(entql.HasEdge("absence_type"))
}

// WhereHasAbsenceTypeWith applies a predicate to check if query has an edge absence_type with a given conditions (other predicates).
func (f *LeaveRequestFilter) WhereHasAbsenceTypeWith(preds ...predicate.AbsenceType) {
	f.Where(entql.HasEdgeWith("absence_type", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
