// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaverequest"
)

// LeaveRequest is the model entity for the LeaveRequest schema.
type LeaveRequest struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// FK to Portal User
	UserID uint32 `json:"user_id,omitempty"`
	// Denormalized user display name
	UserName string `json:"user_name,omitempty"`
	// Denormalized org unit name for grouping
	OrgUnitName string `json:"org_unit_name,omitempty"`
	// FK to AbsenceType
	AbsenceTypeID string `json:"absence_type_id,omitempty"`
	// Start date of absence
	StartDate time.Time `json:"start_date,omitempty"`
	// End date of absence
	EndDate time.Time `json:"end_date,omitempty"`
	// Calculated business days
	Days float64 `json:"days,omitempty"`
	// Request status
	Status leaverequest.Status `json:"status,omitempty"`
	// Paperless signing request ID
	SigningRequestID string `json:"signing_request_id,omitempty"`
	// User's reason for request
	Reason string `json:"reason,omitempty"`
	// HR admin's review notes
	ReviewNotes string `json:"review_notes,omitempty"`
	// User ID of reviewer
	ReviewedBy uint32 `json:"reviewed_by,omitempty"`
	// Denormalized reviewer display name
	ReviewerName string `json:"reviewer_name,omitempty"`
	// When the request was reviewed
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// Additional notes
	Notes string `json:"notes,omitempty"`
	// Custom metadata (JSON)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LeaveRequestQuery when eager-loading is set.
	Edges        LeaveRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LeaveRequestEdges holds the relations/edges for other nodes in the graph.
type LeaveRequestEdges struct {
	// AbsenceType holds the value of the absence_type edge.
	AbsenceType *AbsenceType `json:"absence_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AbsenceTypeOrErr returns the AbsenceType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeaveRequestEdges) AbsenceTypeOrErr() (*AbsenceType, error) {
	if e.AbsenceType != nil {
		return e.AbsenceType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: absencetype.Label}
	}
	return nil, &NotLoadedError{edge: "absence_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LeaveRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case leaverequest.FieldMetadata:
			values[i] = new([]byte)
		case leaverequest.FieldDays:
			values[i] = new(sql.NullFloat64)
		case leaverequest.FieldCreateBy, leaverequest.FieldUpdateBy, leaverequest.FieldTenantID, leaverequest.FieldUserID, leaverequest.FieldReviewedBy:
			values[i] = new(sql.NullInt64)
		case leaverequest.FieldID, leaverequest.FieldUserName, leaverequest.FieldOrgUnitName, leaverequest.FieldAbsenceTypeID, leaverequest.FieldStatus, leaverequest.FieldSigningRequestID, leaverequest.FieldReason, leaverequest.FieldReviewNotes, leaverequest.FieldReviewerName, leaverequest.FieldNotes:
			values[i] = new(sql.NullString)
		case leaverequest.FieldCreateTime, leaverequest.FieldUpdateTime, leaverequest.FieldDeleteTime, leaverequest.FieldStartDate, leaverequest.FieldEndDate, leaverequest.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LeaveRequest fields.
func (_m *LeaveRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case leaverequest.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case leaverequest.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case leaverequest.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case leaverequest.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case leaverequest.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case leaverequest.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case leaverequest.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case leaverequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint32(value.Int64)
			}
		case leaverequest.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case leaverequest.FieldOrgUnitName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_unit_name", values[i])
			} else if value.Valid {
				_m.OrgUnitName = value.String
			}
		case leaverequest.FieldAbsenceTypeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field absence_type_id", values[i])
			} else if value.Valid {
				_m.AbsenceTypeID = value.String
			}
		case leaverequest.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case leaverequest.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = value.Time
			}
		case leaverequest.FieldDays:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field days", values[i])
			} else if value.Valid {
				_m.Days = value.Float64
			}
		case leaverequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = leaverequest.Status(value.String)
			}
		case leaverequest.FieldSigningRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signing_request_id", values[i])
			} else if value.Valid {
				_m.SigningRequestID = value.String
			}
		case leaverequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case leaverequest.FieldReviewNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_notes", values[i])
			} else if value.Valid {
				_m.ReviewNotes = value.String
			}
		case leaverequest.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = uint32(value.Int64)
			}
		case leaverequest.FieldReviewerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reviewer_name", values[i])
			} else if value.Valid {
				_m.ReviewerName = value.String
			}
		case leaverequest.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case leaverequest.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case leaverequest.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LeaveRequest.
// This includes values selected through modifiers, order, etc.
func (_m *LeaveRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAbsenceType queries the "absence_type" edge of the LeaveRequest entity.
func (_m *LeaveRequest) QueryAbsenceType() *AbsenceTypeQuery {
	return NewLeaveRequestClient(_m.config).QueryAbsenceType(_m)
}

// Update returns a builder for updating this LeaveRequest.
// Note that you need to call LeaveRequest.Unwrap() before calling this method if this LeaveRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LeaveRequest) Update() *LeaveRequestUpdateOne {
	return NewLeaveRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LeaveRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LeaveRequest) Unwrap() *LeaveRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LeaveRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LeaveRequest) String() string {
	var builder strings.Builder
	builder.WriteString("LeaveRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("org_unit_name=")
	builder.WriteString(_m.OrgUnitName)
	builder.WriteString(", ")
	builder.WriteString("absence_type_id=")
	builder.WriteString(_m.AbsenceTypeID)
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_date=")
	builder.WriteString(_m.EndDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("days=")
	builder.WriteString(fmt.Sprintf("%v", _m.Days))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("signing_request_id=")
	builder.WriteString(_m.SigningRequestID)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("review_notes=")
	builder.WriteString(_m.ReviewNotes)
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewedBy))
	builder.WriteString(", ")
	builder.WriteString("reviewer_name=")
	builder.WriteString(_m.ReviewerName)
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// LeaveRequests is a parsable slice of LeaveRequest.
type LeaveRequests []*LeaveRequest
