// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaverequest"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"
)

// LeaveRequestUpdate is the builder for updating LeaveRequest entities.
type LeaveRequestUpdate struct {
	config
	hooks     []Hook
	mutation  *LeaveRequestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LeaveRequestUpdate builder.
func (_u *LeaveRequestUpdate) Where(ps ...predicate.LeaveRequest) *LeaveRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *LeaveRequestUpdate) SetCreateBy(v uint32) *LeaveRequestUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableCreateBy(v *uint32) *LeaveRequestUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *LeaveRequestUpdate) AddCreateBy(v int32) *LeaveRequestUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *LeaveRequestUpdate) ClearCreateBy() *LeaveRequestUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *LeaveRequestUpdate) SetUpdateBy(v uint32) *LeaveRequestUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableUpdateBy(v *uint32) *LeaveRequestUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *LeaveRequestUpdate) AddUpdateBy(v int32) *LeaveRequestUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *LeaveRequestUpdate) ClearUpdateBy() *LeaveRequestUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *LeaveRequestUpdate) SetUpdateTime(v time.Time) *LeaveRequestUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableUpdateTime(v *time.Time) *LeaveRequestUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *LeaveRequestUpdate) ClearUpdateTime() *LeaveRequestUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *LeaveRequestUpdate) SetDeleteTime(v time.Time) *LeaveRequestUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableDeleteTime(v *time.Time) *LeaveRequestUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *LeaveRequestUpdate) ClearDeleteTime() *LeaveRequestUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LeaveRequestUpdate) SetUserID(v uint32) *LeaveRequestUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableUserID(v *uint32) *LeaveRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LeaveRequestUpdate) AddUserID(v int32) *LeaveRequestUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *LeaveRequestUpdate) SetUserName(v string) *LeaveRequestUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableUserName(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *LeaveRequestUpdate) ClearUserName() *LeaveRequestUpdate {
	_u.mutation.ClearUserName()
	return _u
}

// SetOrgUnitName sets the "org_unit_name" field.
func (_u *LeaveRequestUpdate) SetOrgUnitName(v string) *LeaveRequestUpdate {
	_u.mutation.SetOrgUnitName(v)
	return _u
}

// SetNillableOrgUnitName sets the "org_unit_name" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableOrgUnitName(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetOrgUnitName(*v)
	}
	return _u
}

// ClearOrgUnitName clears the value of the "org_unit_name" field.
func (_u *LeaveRequestUpdate) ClearOrgUnitName() *LeaveRequestUpdate {
	_u.mutation.ClearOrgUnitName()
	return _u
}

// SetAbsenceTypeID sets the "absence_type_id" field.
func (_u *LeaveRequestUpdate) SetAbsenceTypeID(v string) *LeaveRequestUpdate {
	_u.mutation.SetAbsenceTypeID(v)
	return _u
}

// SetNillableAbsenceTypeID sets the "absence_type_id" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableAbsenceTypeID(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetAbsenceTypeID(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *LeaveRequestUpdate) SetStartDate(v time.Time) *LeaveRequestUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableStartDate(v *time.Time) *LeaveRequestUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *LeaveRequestUpdate) SetEndDate(v time.Time) *LeaveRequestUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableEndDate(v *time.Time) *LeaveRequestUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetDays sets the "days" field.
func (_u *LeaveRequestUpdate) SetDays(v float64) *LeaveRequestUpdate {
	_u.mutation.ResetDays()
	_u.mutation.SetDays(v)
	return _u
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableDays(v *float64) *LeaveRequestUpdate {
	if v != nil {
		_u.SetDays(*v)
	}
	return _u
}

// AddDays adds value to the "days" field.
func (_u *LeaveRequestUpdate) AddDays(v float64) *LeaveRequestUpdate {
	_u.mutation.AddDays(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *LeaveRequestUpdate) SetStatus(v leaverequest.Status) *LeaveRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableStatus(v *leaverequest.Status) *LeaveRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSigningRequestID sets the "signing_request_id" field.
func (_u *LeaveRequestUpdate) SetSigningRequestID(v string) *LeaveRequestUpdate {
	_u.mutation.SetSigningRequestID(v)
	return _u
}

// SetNillableSigningRequestID sets the "signing_request_id" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableSigningRequestID(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetSigningRequestID(*v)
	}
	return _u
}

// ClearSigningRequestID clears the value of the "signing_request_id" field.
func (_u *LeaveRequestUpdate) ClearSigningRequestID() *LeaveRequestUpdate {
	_u.mutation.ClearSigningRequestID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *LeaveRequestUpdate) SetReason(v string) *LeaveRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableReason(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *LeaveRequestUpdate) ClearReason() *LeaveRequestUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *LeaveRequestUpdate) SetReviewNotes(v string) *LeaveRequestUpdate {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableReviewNotes(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// ClearReviewNotes clears the value of the "review_notes" field.
func (_u *LeaveRequestUpdate) ClearReviewNotes() *LeaveRequestUpdate {
	_u.mutation.ClearReviewNotes()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *LeaveRequestUpdate) SetReviewedBy(v uint32) *LeaveRequestUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableReviewedBy(v *uint32) *LeaveRequestUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *LeaveRequestUpdate) AddReviewedBy(v int32) *LeaveRequestUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *LeaveRequestUpdate) ClearReviewedBy() *LeaveRequestUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewerName sets the "reviewer_name" field.
func (_u *LeaveRequestUpdate) SetReviewerName(v string) *LeaveRequestUpdate {
	_u.mutation.SetReviewerName(v)
	return _u
}

// SetNillableReviewerName sets the "reviewer_name" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableReviewerName(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetReviewerName(*v)
	}
	return _u
}

// ClearReviewerName clears the value of the "reviewer_name" field.
func (_u *LeaveRequestUpdate) ClearReviewerName() *LeaveRequestUpdate {
	_u.mutation.ClearReviewerName()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *LeaveRequestUpdate) SetReviewedAt(v time.Time) *LeaveRequestUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableReviewedAt(v *time.Time) *LeaveRequestUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *LeaveRequestUpdate) ClearReviewedAt() *LeaveRequestUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LeaveRequestUpdate) SetNotes(v string) *LeaveRequestUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LeaveRequestUpdate) SetNillableNotes(v *string) *LeaveRequestUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *LeaveRequestUpdate) ClearNotes() *LeaveRequestUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LeaveRequestUpdate) SetMetadata(v map[string]interface{}) *LeaveRequestUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *LeaveRequestUpdate) ClearMetadata() *LeaveRequestUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetAbsenceType sets the "absence_type" edge to the AbsenceType entity.
func (_u *LeaveRequestUpdate) SetAbsenceType(v *AbsenceType) *LeaveRequestUpdate {
	return _u.SetAbsenceTypeID(v.ID)
}

// Mutation returns the LeaveRequestMutation object of the builder.
func (_u *LeaveRequestUpdate) Mutation() *LeaveRequestMutation {
	return _u.mutation
}

// ClearAbsenceType clears the "absence_type" edge to the AbsenceType entity.
func (_u *LeaveRequestUpdate) ClearAbsenceType() *LeaveRequestUpdate {
	_u.mutation.ClearAbsenceType()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LeaveRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LeaveRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LeaveRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LeaveRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LeaveRequestUpdate) check() error {
	if v, ok := _u.mutation.AbsenceTypeID(); ok {
		if err := leaverequest.AbsenceTypeIDValidator(v); err != nil {
			return &ValidationError{Name: "absence_type_id", err: fmt.Errorf(`ent: validator failed for field "LeaveRequest.absence_type_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := leaverequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LeaveRequest.status": %w`, err)}
		}
	}
	if _u.mutation.AbsenceTypeCleared() && len(_u.mutation.AbsenceTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LeaveRequest.absence_type"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LeaveRequestUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LeaveRequestUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LeaveRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(leaverequest.Table, leaverequest.Columns, sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(leaverequest.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(leaverequest.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(leaverequest.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(leaverequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(leaverequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(leaverequest.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(leaverequest.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(leaverequest.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(leaverequest.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(leaverequest.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(leaverequest.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(leaverequest.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(leaverequest.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(leaverequest.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(leaverequest.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(leaverequest.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.OrgUnitName(); ok {
		_spec.SetField(leaverequest.FieldOrgUnitName, field.TypeString, value)
	}
	if _u.mutation.OrgUnitNameCleared() {
		_spec.ClearField(leaverequest.FieldOrgUnitName, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(leaverequest.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(leaverequest.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Days(); ok {
		_spec.SetField(leaverequest.FieldDays, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDays(); ok {
		_spec.AddField(leaverequest.FieldDays, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(leaverequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SigningRequestID(); ok {
		_spec.SetField(leaverequest.FieldSigningRequestID, field.TypeString, value)
	}
	if _u.mutation.SigningRequestIDCleared() {
		_spec.ClearField(leaverequest.FieldSigningRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(leaverequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(leaverequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(leaverequest.FieldReviewNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewNotesCleared() {
		_spec.ClearField(leaverequest.FieldReviewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(leaverequest.FieldReviewedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(leaverequest.FieldReviewedBy, field.TypeUint32, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(leaverequest.FieldReviewedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.ReviewerName(); ok {
		_spec.SetField(leaverequest.FieldReviewerName, field.TypeString, value)
	}
	if _u.mutation.ReviewerNameCleared() {
		_spec.ClearField(leaverequest.FieldReviewerName, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(leaverequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(leaverequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(leaverequest.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(leaverequest.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(leaverequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(leaverequest.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.AbsenceTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaverequest.AbsenceTypeTable,
			Columns: []string{leaverequest.AbsenceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AbsenceTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaverequest.AbsenceTypeTable,
			Columns: []string{leaverequest.AbsenceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{leaverequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LeaveRequestUpdateOne is the builder for updating a single LeaveRequest entity.
type LeaveRequestUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LeaveRequestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *LeaveRequestUpdateOne) SetCreateBy(v uint32) *LeaveRequestUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableCreateBy(v *uint32) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *LeaveRequestUpdateOne) AddCreateBy(v int32) *LeaveRequestUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *LeaveRequestUpdateOne) ClearCreateBy() *LeaveRequestUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *LeaveRequestUpdateOne) SetUpdateBy(v uint32) *LeaveRequestUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableUpdateBy(v *uint32) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *LeaveRequestUpdateOne) AddUpdateBy(v int32) *LeaveRequestUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *LeaveRequestUpdateOne) ClearUpdateBy() *LeaveRequestUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *LeaveRequestUpdateOne) SetUpdateTime(v time.Time) *LeaveRequestUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableUpdateTime(v *time.Time) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *LeaveRequestUpdateOne) ClearUpdateTime() *LeaveRequestUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *LeaveRequestUpdateOne) SetDeleteTime(v time.Time) *LeaveRequestUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableDeleteTime(v *time.Time) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *LeaveRequestUpdateOne) ClearDeleteTime() *LeaveRequestUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LeaveRequestUpdateOne) SetUserID(v uint32) *LeaveRequestUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableUserID(v *uint32) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LeaveRequestUpdateOne) AddUserID(v int32) *LeaveRequestUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *LeaveRequestUpdateOne) SetUserName(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableUserName(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *LeaveRequestUpdateOne) ClearUserName() *LeaveRequestUpdateOne {
	_u.mutation.ClearUserName()
	return _u
}

// SetOrgUnitName sets the "org_unit_name" field.
func (_u *LeaveRequestUpdateOne) SetOrgUnitName(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetOrgUnitName(v)
	return _u
}

// SetNillableOrgUnitName sets the "org_unit_name" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableOrgUnitName(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetOrgUnitName(*v)
	}
	return _u
}

// ClearOrgUnitName clears the value of the "org_unit_name" field.
func (_u *LeaveRequestUpdateOne) ClearOrgUnitName() *LeaveRequestUpdateOne {
	_u.mutation.ClearOrgUnitName()
	return _u
}

// SetAbsenceTypeID sets the "absence_type_id" field.
func (_u *LeaveRequestUpdateOne) SetAbsenceTypeID(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetAbsenceTypeID(v)
	return _u
}

// SetNillableAbsenceTypeID sets the "absence_type_id" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableAbsenceTypeID(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetAbsenceTypeID(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *LeaveRequestUpdateOne) SetStartDate(v time.Time) *LeaveRequestUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableStartDate(v *time.Time) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *LeaveRequestUpdateOne) SetEndDate(v time.Time) *LeaveRequestUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableEndDate(v *time.Time) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetDays sets the "days" field.
func (_u *LeaveRequestUpdateOne) SetDays(v float64) *LeaveRequestUpdateOne {
	_u.mutation.ResetDays()
	_u.mutation.SetDays(v)
	return _u
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableDays(v *float64) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetDays(*v)
	}
	return _u
}

// AddDays adds value to the "days" field.
func (_u *LeaveRequestUpdateOne) AddDays(v float64) *LeaveRequestUpdateOne {
	_u.mutation.AddDays(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *LeaveRequestUpdateOne) SetStatus(v leaverequest.Status) *LeaveRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableStatus(v *leaverequest.Status) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSigningRequestID sets the "signing_request_id" field.
func (_u *LeaveRequestUpdateOne) SetSigningRequestID(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetSigningRequestID(v)
	return _u
}

// SetNillableSigningRequestID sets the "signing_request_id" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableSigningRequestID(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetSigningRequestID(*v)
	}
	return _u
}

// ClearSigningRequestID clears the value of the "signing_request_id" field.
func (_u *LeaveRequestUpdateOne) ClearSigningRequestID() *LeaveRequestUpdateOne {
	_u.mutation.ClearSigningRequestID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *LeaveRequestUpdateOne) SetReason(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableReason(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *LeaveRequestUpdateOne) ClearReason() *LeaveRequestUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *LeaveRequestUpdateOne) SetReviewNotes(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableReviewNotes(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// ClearReviewNotes clears the value of the "review_notes" field.
func (_u *LeaveRequestUpdateOne) ClearReviewNotes() *LeaveRequestUpdateOne {
	_u.mutation.ClearReviewNotes()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *LeaveRequestUpdateOne) SetReviewedBy(v uint32) *LeaveRequestUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableReviewedBy(v *uint32) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *LeaveRequestUpdateOne) AddReviewedBy(v int32) *LeaveRequestUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *LeaveRequestUpdateOne) ClearReviewedBy() *LeaveRequestUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewerName sets the "reviewer_name" field.
func (_u *LeaveRequestUpdateOne) SetReviewerName(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetReviewerName(v)
	return _u
}

// SetNillableReviewerName sets the "reviewer_name" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableReviewerName(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetReviewerName(*v)
	}
	return _u
}

// ClearReviewerName clears the value of the "reviewer_name" field.
func (_u *LeaveRequestUpdateOne) ClearReviewerName() *LeaveRequestUpdateOne {
	_u.mutation.ClearReviewerName()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *LeaveRequestUpdateOne) SetReviewedAt(v time.Time) *LeaveRequestUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableReviewedAt(v *time.Time) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *LeaveRequestUpdateOne) ClearReviewedAt() *LeaveRequestUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LeaveRequestUpdateOne) SetNotes(v string) *LeaveRequestUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LeaveRequestUpdateOne) SetNillableNotes(v *string) *LeaveRequestUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *LeaveRequestUpdateOne) ClearNotes() *LeaveRequestUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LeaveRequestUpdateOne) SetMetadata(v map[string]interface{}) *LeaveRequestUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *LeaveRequestUpdateOne) ClearMetadata() *LeaveRequestUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetAbsenceType sets the "absence_type" edge to the AbsenceType entity.
func (_u *LeaveRequestUpdateOne) SetAbsenceType(v *AbsenceType) *LeaveRequestUpdateOne {
	return _u.SetAbsenceTypeID(v.ID)
}

// Mutation returns the LeaveRequestMutation object of the builder.
func (_u *LeaveRequestUpdateOne) Mutation() *LeaveRequestMutation {
	return _u.mutation
}

// ClearAbsenceType clears the "absence_type" edge to the AbsenceType entity.
func (_u *LeaveRequestUpdateOne) ClearAbsenceType() *LeaveRequestUpdateOne {
	_u.mutation.ClearAbsenceType()
	return _u
}

// Where appends a list predicates to the LeaveRequestUpdate builder.
func (_u *LeaveRequestUpdateOne) Where(ps ...predicate.LeaveRequest) *LeaveRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LeaveRequestUpdateOne) Select(field string, fields ...string) *LeaveRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LeaveRequest entity.
func (_u *LeaveRequestUpdateOne) Save(ctx context.Context) (*LeaveRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LeaveRequestUpdateOne) SaveX(ctx context.Context) *LeaveRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LeaveRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LeaveRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LeaveRequestUpdateOne) check() error {
	if v, ok := _u.mutation.AbsenceTypeID(); ok {
		if err := leaverequest.AbsenceTypeIDValidator(v); err != nil {
			return &ValidationError{Name: "absence_type_id", err: fmt.Errorf(`ent: validator failed for field "LeaveRequest.absence_type_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := leaverequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LeaveRequest.status": %w`, err)}
		}
	}
	if _u.mutation.AbsenceTypeCleared() && len(_u.mutation.AbsenceTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LeaveRequest.absence_type"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LeaveRequestUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LeaveRequestUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LeaveRequestUpdateOne) sqlSave(ctx context.Context) (_node *LeaveRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(leaverequest.Table, leaverequest.Columns, sqlgraph.NewFieldSpec(leaverequest.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LeaveRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, leaverequest.FieldID)
		for _, f := range fields {
			if !leaverequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != leaverequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(leaverequest.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(leaverequest.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(leaverequest.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(leaverequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(leaverequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(leaverequest.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(leaverequest.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(leaverequest.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(leaverequest.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(leaverequest.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(leaverequest.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(leaverequest.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(leaverequest.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(leaverequest.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(leaverequest.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(leaverequest.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.OrgUnitName(); ok {
		_spec.SetField(leaverequest.FieldOrgUnitName, field.TypeString, value)
	}
	if _u.mutation.OrgUnitNameCleared() {
		_spec.ClearField(leaverequest.FieldOrgUnitName, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(leaverequest.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(leaverequest.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Days(); ok {
		_spec.SetField(leaverequest.FieldDays, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDays(); ok {
		_spec.AddField(leaverequest.FieldDays, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(leaverequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SigningRequestID(); ok {
		_spec.SetField(leaverequest.FieldSigningRequestID, field.TypeString, value)
	}
	if _u.mutation.SigningRequestIDCleared() {
		_spec.ClearField(leaverequest.FieldSigningRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(leaverequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(leaverequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(leaverequest.FieldReviewNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewNotesCleared() {
		_spec.ClearField(leaverequest.FieldReviewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(leaverequest.FieldReviewedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(leaverequest.FieldReviewedBy, field.TypeUint32, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(leaverequest.FieldReviewedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.ReviewerName(); ok {
		_spec.SetField(leaverequest.FieldReviewerName, field.TypeString, value)
	}
	if _u.mutation.ReviewerNameCleared() {
		_spec.ClearField(leaverequest.FieldReviewerName, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(leaverequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(leaverequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(leaverequest.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(leaverequest.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(leaverequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(leaverequest.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.AbsenceTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaverequest.AbsenceTypeTable,
			Columns: []string{leaverequest.AbsenceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AbsenceTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   leaverequest.AbsenceTypeTable,
			Columns: []string{leaverequest.AbsenceTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(absencetype.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &LeaveRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{leaverequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
