// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/absencetype"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/leaveallowance"
)

// LeaveAllowance is the model entity for the LeaveAllowance schema.
type LeaveAllowance struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// FK to Portal User
	UserID uint32 `json:"user_id,omitempty"`
	// Denormalized user display name
	UserName string `json:"user_name,omitempty"`
	// FK to AbsenceType
	AbsenceTypeID string `json:"absence_type_id,omitempty"`
	// Calendar year
	Year int `json:"year,omitempty"`
	// Total allowed days (supports half-days)
	TotalDays float64 `json:"total_days,omitempty"`
	// Consumed days
	UsedDays float64 `json:"used_days,omitempty"`
	// Carried from previous year
	CarriedOver float64 `json:"carried_over,omitempty"`
	// Notes
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LeaveAllowanceQuery when eager-loading is set.
	Edges        LeaveAllowanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LeaveAllowanceEdges holds the relations/edges for other nodes in the graph.
type LeaveAllowanceEdges struct {
	// AbsenceType holds the value of the absence_type edge.
	AbsenceType *AbsenceType `json:"absence_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AbsenceTypeOrErr returns the AbsenceType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeaveAllowanceEdges) AbsenceTypeOrErr() (*AbsenceType, error) {
	if e.AbsenceType != nil {
		return e.AbsenceType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: absencetype.Label}
	}
	return nil, &NotLoadedError{edge: "absence_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LeaveAllowance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case leaveallowance.FieldTotalDays, leaveallowance.FieldUsedDays, leaveallowance.FieldCarriedOver:
			values[i] = new(sql.NullFloat64)
		case leaveallowance.FieldCreateBy, leaveallowance.FieldUpdateBy, leaveallowance.FieldTenantID, leaveallowance.FieldUserID, leaveallowance.FieldYear:
			values[i] = new(sql.NullInt64)
		case leaveallowance.FieldID, leaveallowance.FieldUserName, leaveallowance.FieldAbsenceTypeID, leaveallowance.FieldNotes:
			values[i] = new(sql.NullString)
		case leaveallowance.FieldCreateTime, leaveallowance.FieldUpdateTime, leaveallowance.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LeaveAllowance fields.
func (_m *LeaveAllowance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case leaveallowance.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case leaveallowance.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case leaveallowance.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case leaveallowance.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case leaveallowance.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case leaveallowance.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case leaveallowance.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case leaveallowance.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint32(value.Int64)
			}
		case leaveallowance.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case leaveallowance.FieldAbsenceTypeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field absence_type_id", values[i])
			} else if value.Valid {
				_m.AbsenceTypeID = value.String
			}
		case leaveallowance.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = int(value.Int64)
			}
		case leaveallowance.FieldTotalDays:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_days", values[i])
			} else if value.Valid {
				_m.TotalDays = value.Float64
			}
		case leaveallowance.FieldUsedDays:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_days", values[i])
			} else if value.Valid {
				_m.UsedDays = value.Float64
			}
		case leaveallowance.FieldCarriedOver:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field carried_over", values[i])
			} else if value.Valid {
				_m.CarriedOver = value.Float64
			}
		case leaveallowance.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LeaveAllowance.
// This includes values selected through modifiers, order, etc.
func (_m *LeaveAllowance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAbsenceType queries the "absence_type" edge of the LeaveAllowance entity.
func (_m *LeaveAllowance) QueryAbsenceType() *AbsenceTypeQuery {
	return NewLeaveAllowanceClient(_m.config).QueryAbsenceType(_m)
}

// Update returns a builder for updating this LeaveAllowance.
// Note that you need to call LeaveAllowance.Unwrap() before calling this method if this LeaveAllowance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LeaveAllowance) Update() *LeaveAllowanceUpdateOne {
	return NewLeaveAllowanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LeaveAllowance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LeaveAllowance) Unwrap() *LeaveAllowance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LeaveAllowance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LeaveAllowance) String() string {
	var builder strings.Builder
	builder.WriteString("LeaveAllowance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("absence_type_id=")
	builder.WriteString(_m.AbsenceTypeID)
	builder.WriteString(", ")
	builder.WriteString("year=")
	builder.WriteString(fmt.Sprintf("%v", _m.Year))
	builder.WriteString(", ")
	builder.WriteString("total_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalDays))
	builder.WriteString(", ")
	builder.WriteString("used_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedDays))
	builder.WriteString(", ")
	builder.WriteString("carried_over=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarriedOver))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// LeaveAllowances is a parsable slice of LeaveAllowance.
type LeaveAllowances []*LeaveAllowance
