// Code generated by ent, DO NOT EDIT.

package allowancepool

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the allowancepool type in the database.
	Label = "allowance_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// EdgeAbsenceTypes holds the string denoting the absence_types edge name in mutations.
	EdgeAbsenceTypes = "absence_types"
	// EdgeLeaveAllowances holds the string denoting the leave_allowances edge name in mutations.
	EdgeLeaveAllowances = "leave_allowances"
	// Table holds the table name of the allowancepool in the database.
	Table = "hr_allowance_pools"
	// AbsenceTypesTable is the table that holds the absence_types relation/edge.
	AbsenceTypesTable = "hr_absence_types"
	// AbsenceTypesInverseTable is the table name for the AbsenceType entity.
	// It exists in this package in order to avoid circular dependency with the "absencetype" package.
	AbsenceTypesInverseTable = "hr_absence_types"
	// AbsenceTypesColumn is the table column denoting the absence_types relation/edge.
	AbsenceTypesColumn = "allowance_pool_id"
	// LeaveAllowancesTable is the table that holds the leave_allowances relation/edge.
	LeaveAllowancesTable = "hr_leave_allowances"
	// LeaveAllowancesInverseTable is the table name for the LeaveAllowance entity.
	// It exists in this package in order to avoid circular dependency with the "leaveallowance" package.
	LeaveAllowancesInverseTable = "hr_leave_allowances"
	// LeaveAllowancesColumn is the table column denoting the leave_allowances relation/edge.
	LeaveAllowancesColumn = "allowance_pool_id"
)

// Columns holds all SQL columns for allowancepool fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldUpdateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldName,
	FieldDescription,
	FieldColor,
	FieldIcon,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-hr/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ColorValidator is a validator for the "color" field. It is called by the builders before save.
	ColorValidator func(string) error
	// IconValidator is a validator for the "icon" field. It is called by the builders before save.
	IconValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AllowancePool queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByAbsenceTypesCount orders the results by absence_types count.
func ByAbsenceTypesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAbsenceTypesStep(), opts...)
	}
}

// ByAbsenceTypes orders the results by absence_types terms.
func ByAbsenceTypes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAbsenceTypesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLeaveAllowancesCount orders the results by leave_allowances count.
func ByLeaveAllowancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLeaveAllowancesStep(), opts...)
	}
}

// ByLeaveAllowances orders the results by leave_allowances terms.
func ByLeaveAllowances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLeaveAllowancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAbsenceTypesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AbsenceTypesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AbsenceTypesTable, AbsenceTypesColumn),
	)
}
func newLeaveAllowancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LeaveAllowancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LeaveAllowancesTable, LeaveAllowancesColumn),
	)
}
