// Code generated by ent, DO NOT EDIT.

package leaveallowance

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the leaveallowance type in the database.
	Label = "leave_allowance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldAbsenceTypeID holds the string denoting the absence_type_id field in the database.
	FieldAbsenceTypeID = "absence_type_id"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldTotalDays holds the string denoting the total_days field in the database.
	FieldTotalDays = "total_days"
	// FieldUsedDays holds the string denoting the used_days field in the database.
	FieldUsedDays = "used_days"
	// FieldCarriedOver holds the string denoting the carried_over field in the database.
	FieldCarriedOver = "carried_over"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeAbsenceType holds the string denoting the absence_type edge name in mutations.
	EdgeAbsenceType = "absence_type"
	// Table holds the table name of the leaveallowance in the database.
	Table = "hr_leave_allowances"
	// AbsenceTypeTable is the table that holds the absence_type relation/edge.
	AbsenceTypeTable = "hr_leave_allowances"
	// AbsenceTypeInverseTable is the table name for the AbsenceType entity.
	// It exists in this package in order to avoid circular dependency with the "absencetype" package.
	AbsenceTypeInverseTable = "hr_absence_types"
	// AbsenceTypeColumn is the table column denoting the absence_type relation/edge.
	AbsenceTypeColumn = "absence_type_id"
)

// Columns holds all SQL columns for leaveallowance fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldUpdateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldUserID,
	FieldUserName,
	FieldAbsenceTypeID,
	FieldYear,
	FieldTotalDays,
	FieldUsedDays,
	FieldCarriedOver,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-hr/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// DefaultUserName holds the default value on creation for the "user_name" field.
	DefaultUserName string
	// AbsenceTypeIDValidator is a validator for the "absence_type_id" field. It is called by the builders before save.
	AbsenceTypeIDValidator func(string) error
	// YearValidator is a validator for the "year" field. It is called by the builders before save.
	YearValidator func(int) error
	// DefaultUsedDays holds the default value on creation for the "used_days" field.
	DefaultUsedDays float64
	// DefaultCarriedOver holds the default value on creation for the "carried_over" field.
	DefaultCarriedOver float64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the LeaveAllowance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByAbsenceTypeID orders the results by the absence_type_id field.
func ByAbsenceTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbsenceTypeID, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByTotalDays orders the results by the total_days field.
func ByTotalDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDays, opts...).ToFunc()
}

// ByUsedDays orders the results by the used_days field.
func ByUsedDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedDays, opts...).ToFunc()
}

// ByCarriedOver orders the results by the carried_over field.
func ByCarriedOver(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCarriedOver, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByAbsenceTypeField orders the results by absence_type field.
func ByAbsenceTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAbsenceTypeStep(), sql.OrderByField(field, opts...))
	}
}
func newAbsenceTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AbsenceTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AbsenceTypeTable, AbsenceTypeColumn),
	)
}
