// Code generated by ent, DO NOT EDIT.

package leaveallowance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUpdateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUserID, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUserName, v))
}

// AbsenceTypeID applies equality check predicate on the "absence_type_id" field. It's identical to AbsenceTypeIDEQ.
func AbsenceTypeID(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldAbsenceTypeID, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldYear, v))
}

// TotalDays applies equality check predicate on the "total_days" field. It's identical to TotalDaysEQ.
func TotalDays(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldTotalDays, v))
}

// UsedDays applies equality check predicate on the "used_days" field. It's identical to UsedDaysEQ.
func UsedDays(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUsedDays, v))
}

// CarriedOver applies equality check predicate on the "carried_over" field. It's identical to CarriedOverEQ.
func CarriedOver(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldCarriedOver, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldNotes, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldCreateBy))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldUpdateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldTenantID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldUserID, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameIsNil applies the IsNil predicate on the "user_name" field.
func UserNameIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldUserName))
}

// UserNameNotNil applies the NotNil predicate on the "user_name" field.
func UserNameNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldUserName))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContainsFold(FieldUserName, v))
}

// AbsenceTypeIDEQ applies the EQ predicate on the "absence_type_id" field.
func AbsenceTypeIDEQ(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDNEQ applies the NEQ predicate on the "absence_type_id" field.
func AbsenceTypeIDNEQ(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDIn applies the In predicate on the "absence_type_id" field.
func AbsenceTypeIDIn(vs ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldAbsenceTypeID, vs...))
}

// AbsenceTypeIDNotIn applies the NotIn predicate on the "absence_type_id" field.
func AbsenceTypeIDNotIn(vs ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldAbsenceTypeID, vs...))
}

// AbsenceTypeIDGT applies the GT predicate on the "absence_type_id" field.
func AbsenceTypeIDGT(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDGTE applies the GTE predicate on the "absence_type_id" field.
func AbsenceTypeIDGTE(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDLT applies the LT predicate on the "absence_type_id" field.
func AbsenceTypeIDLT(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDLTE applies the LTE predicate on the "absence_type_id" field.
func AbsenceTypeIDLTE(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDContains applies the Contains predicate on the "absence_type_id" field.
func AbsenceTypeIDContains(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContains(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDHasPrefix applies the HasPrefix predicate on the "absence_type_id" field.
func AbsenceTypeIDHasPrefix(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldHasPrefix(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDHasSuffix applies the HasSuffix predicate on the "absence_type_id" field.
func AbsenceTypeIDHasSuffix(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldHasSuffix(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDEqualFold applies the EqualFold predicate on the "absence_type_id" field.
func AbsenceTypeIDEqualFold(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEqualFold(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDContainsFold applies the ContainsFold predicate on the "absence_type_id" field.
func AbsenceTypeIDContainsFold(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContainsFold(FieldAbsenceTypeID, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldYear, v))
}

// TotalDaysEQ applies the EQ predicate on the "total_days" field.
func TotalDaysEQ(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldTotalDays, v))
}

// TotalDaysNEQ applies the NEQ predicate on the "total_days" field.
func TotalDaysNEQ(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldTotalDays, v))
}

// TotalDaysIn applies the In predicate on the "total_days" field.
func TotalDaysIn(vs ...float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldTotalDays, vs...))
}

// TotalDaysNotIn applies the NotIn predicate on the "total_days" field.
func TotalDaysNotIn(vs ...float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldTotalDays, vs...))
}

// TotalDaysGT applies the GT predicate on the "total_days" field.
func TotalDaysGT(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldTotalDays, v))
}

// TotalDaysGTE applies the GTE predicate on the "total_days" field.
func TotalDaysGTE(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldTotalDays, v))
}

// TotalDaysLT applies the LT predicate on the "total_days" field.
func TotalDaysLT(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldTotalDays, v))
}

// TotalDaysLTE applies the LTE predicate on the "total_days" field.
func TotalDaysLTE(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldTotalDays, v))
}

// UsedDaysEQ applies the EQ predicate on the "used_days" field.
func UsedDaysEQ(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldUsedDays, v))
}

// UsedDaysNEQ applies the NEQ predicate on the "used_days" field.
func UsedDaysNEQ(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldUsedDays, v))
}

// UsedDaysIn applies the In predicate on the "used_days" field.
func UsedDaysIn(vs ...float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldUsedDays, vs...))
}

// UsedDaysNotIn applies the NotIn predicate on the "used_days" field.
func UsedDaysNotIn(vs ...float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldUsedDays, vs...))
}

// UsedDaysGT applies the GT predicate on the "used_days" field.
func UsedDaysGT(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldUsedDays, v))
}

// UsedDaysGTE applies the GTE predicate on the "used_days" field.
func UsedDaysGTE(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldUsedDays, v))
}

// UsedDaysLT applies the LT predicate on the "used_days" field.
func UsedDaysLT(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldUsedDays, v))
}

// UsedDaysLTE applies the LTE predicate on the "used_days" field.
func UsedDaysLTE(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldUsedDays, v))
}

// CarriedOverEQ applies the EQ predicate on the "carried_over" field.
func CarriedOverEQ(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldCarriedOver, v))
}

// CarriedOverNEQ applies the NEQ predicate on the "carried_over" field.
func CarriedOverNEQ(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldCarriedOver, v))
}

// CarriedOverIn applies the In predicate on the "carried_over" field.
func CarriedOverIn(vs ...float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldCarriedOver, vs...))
}

// CarriedOverNotIn applies the NotIn predicate on the "carried_over" field.
func CarriedOverNotIn(vs ...float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldCarriedOver, vs...))
}

// CarriedOverGT applies the GT predicate on the "carried_over" field.
func CarriedOverGT(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldCarriedOver, v))
}

// CarriedOverGTE applies the GTE predicate on the "carried_over" field.
func CarriedOverGTE(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldCarriedOver, v))
}

// CarriedOverLT applies the LT predicate on the "carried_over" field.
func CarriedOverLT(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldCarriedOver, v))
}

// CarriedOverLTE applies the LTE predicate on the "carried_over" field.
func CarriedOverLTE(v float64) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldCarriedOver, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.FieldContainsFold(FieldNotes, v))
}

// HasAbsenceType applies the HasEdge predicate on the "absence_type" edge.
func HasAbsenceType() predicate.LeaveAllowance {
	return predicate.LeaveAllowance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AbsenceTypeTable, AbsenceTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAbsenceTypeWith applies the HasEdge predicate on the "absence_type" edge with a given conditions (other predicates).
func HasAbsenceTypeWith(preds ...predicate.AbsenceType) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(func(s *sql.Selector) {
		step := newAbsenceTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LeaveAllowance) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LeaveAllowance) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LeaveAllowance) predicate.LeaveAllowance {
	return predicate.LeaveAllowance(sql.NotPredicates(p))
}
