// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditlog type in the database.
	Label = "audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldAuditID holds the string denoting the audit_id field in the database.
	FieldAuditID = "audit_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldClientCommonName holds the string denoting the client_common_name field in the database.
	FieldClientCommonName = "client_common_name"
	// FieldClientOrganization holds the string denoting the client_organization field in the database.
	FieldClientOrganization = "client_organization"
	// FieldClientSerialNumber holds the string denoting the client_serial_number field in the database.
	FieldClientSerialNumber = "client_serial_number"
	// FieldIsAuthenticated holds the string denoting the is_authenticated field in the database.
	FieldIsAuthenticated = "is_authenticated"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldPeerAddress holds the string denoting the peer_address field in the database.
	FieldPeerAddress = "peer_address"
	// FieldGeoLocation holds the string denoting the geo_location field in the database.
	FieldGeoLocation = "geo_location"
	// FieldLogHash holds the string denoting the log_hash field in the database.
	FieldLogHash = "log_hash"
	// FieldSignature holds the string denoting the signature field in the database.
	FieldSignature = "signature"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the auditlog in the database.
	Table = "hr_audit_logs"
)

// Columns holds all SQL columns for auditlog fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldAuditID,
	FieldRequestID,
	FieldOperation,
	FieldServiceName,
	FieldClientID,
	FieldClientCommonName,
	FieldClientOrganization,
	FieldClientSerialNumber,
	FieldIsAuthenticated,
	FieldSuccess,
	FieldErrorCode,
	FieldErrorMessage,
	FieldLatencyMs,
	FieldPeerAddress,
	FieldGeoLocation,
	FieldLogHash,
	FieldSignature,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-hr/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// AuditIDValidator is a validator for the "audit_id" field. It is called by the builders before save.
	AuditIDValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// DefaultServiceName holds the default value on creation for the "service_name" field.
	DefaultServiceName string
	// DefaultIsAuthenticated holds the default value on creation for the "is_authenticated" field.
	DefaultIsAuthenticated bool
	// DefaultSuccess holds the default value on creation for the "success" field.
	DefaultSuccess bool
	// DefaultLatencyMs holds the default value on creation for the "latency_ms" field.
	DefaultLatencyMs int64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the AuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByAuditID orders the results by the audit_id field.
func ByAuditID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByClientCommonName orders the results by the client_common_name field.
func ByClientCommonName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientCommonName, opts...).ToFunc()
}

// ByClientOrganization orders the results by the client_organization field.
func ByClientOrganization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientOrganization, opts...).ToFunc()
}

// ByClientSerialNumber orders the results by the client_serial_number field.
func ByClientSerialNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientSerialNumber, opts...).ToFunc()
}

// ByIsAuthenticated orders the results by the is_authenticated field.
func ByIsAuthenticated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAuthenticated, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByPeerAddress orders the results by the peer_address field.
func ByPeerAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeerAddress, opts...).ToFunc()
}

// ByLogHash orders the results by the log_hash field.
func ByLogHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogHash, opts...).ToFunc()
}
