// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldTenantID, v))
}

// AuditID applies equality check predicate on the "audit_id" field. It's identical to AuditIDEQ.
func AuditID(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldAuditID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldRequestID, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldOperation, v))
}

// ServiceName applies equality check predicate on the "service_name" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldServiceName, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientID, v))
}

// ClientCommonName applies equality check predicate on the "client_common_name" field. It's identical to ClientCommonNameEQ.
func ClientCommonName(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientCommonName, v))
}

// ClientOrganization applies equality check predicate on the "client_organization" field. It's identical to ClientOrganizationEQ.
func ClientOrganization(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientOrganization, v))
}

// ClientSerialNumber applies equality check predicate on the "client_serial_number" field. It's identical to ClientSerialNumberEQ.
func ClientSerialNumber(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientSerialNumber, v))
}

// IsAuthenticated applies equality check predicate on the "is_authenticated" field. It's identical to IsAuthenticatedEQ.
func IsAuthenticated(v bool) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldIsAuthenticated, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldSuccess, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldErrorMessage, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldLatencyMs, v))
}

// PeerAddress applies equality check predicate on the "peer_address" field. It's identical to PeerAddressEQ.
func PeerAddress(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldPeerAddress, v))
}

// LogHash applies equality check predicate on the "log_hash" field. It's identical to LogHashEQ.
func LogHash(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldLogHash, v))
}

// Signature applies equality check predicate on the "signature" field. It's identical to SignatureEQ.
func Signature(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldSignature, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldTenantID))
}

// AuditIDEQ applies the EQ predicate on the "audit_id" field.
func AuditIDEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldAuditID, v))
}

// AuditIDNEQ applies the NEQ predicate on the "audit_id" field.
func AuditIDNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldAuditID, v))
}

// AuditIDIn applies the In predicate on the "audit_id" field.
func AuditIDIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldAuditID, vs...))
}

// AuditIDNotIn applies the NotIn predicate on the "audit_id" field.
func AuditIDNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldAuditID, vs...))
}

// AuditIDGT applies the GT predicate on the "audit_id" field.
func AuditIDGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldAuditID, v))
}

// AuditIDGTE applies the GTE predicate on the "audit_id" field.
func AuditIDGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldAuditID, v))
}

// AuditIDLT applies the LT predicate on the "audit_id" field.
func AuditIDLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldAuditID, v))
}

// AuditIDLTE applies the LTE predicate on the "audit_id" field.
func AuditIDLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldAuditID, v))
}

// AuditIDContains applies the Contains predicate on the "audit_id" field.
func AuditIDContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldAuditID, v))
}

// AuditIDHasPrefix applies the HasPrefix predicate on the "audit_id" field.
func AuditIDHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldAuditID, v))
}

// AuditIDHasSuffix applies the HasSuffix predicate on the "audit_id" field.
func AuditIDHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldAuditID, v))
}

// AuditIDEqualFold applies the EqualFold predicate on the "audit_id" field.
func AuditIDEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldAuditID, v))
}

// AuditIDContainsFold applies the ContainsFold predicate on the "audit_id" field.
func AuditIDContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldAuditID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldRequestID, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldOperation, v))
}

// ServiceNameEQ applies the EQ predicate on the "service_name" field.
func ServiceNameEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "service_name" field.
func ServiceNameNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "service_name" field.
func ServiceNameIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "service_name" field.
func ServiceNameNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "service_name" field.
func ServiceNameGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "service_name" field.
func ServiceNameGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "service_name" field.
func ServiceNameLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "service_name" field.
func ServiceNameLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "service_name" field.
func ServiceNameContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "service_name" field.
func ServiceNameHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "service_name" field.
func ServiceNameHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "service_name" field.
func ServiceNameEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "service_name" field.
func ServiceNameContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldServiceName, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDIsNil applies the IsNil predicate on the "client_id" field.
func ClientIDIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldClientID))
}

// ClientIDNotNil applies the NotNil predicate on the "client_id" field.
func ClientIDNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldClientID))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldClientID, v))
}

// ClientCommonNameEQ applies the EQ predicate on the "client_common_name" field.
func ClientCommonNameEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientCommonName, v))
}

// ClientCommonNameNEQ applies the NEQ predicate on the "client_common_name" field.
func ClientCommonNameNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldClientCommonName, v))
}

// ClientCommonNameIn applies the In predicate on the "client_common_name" field.
func ClientCommonNameIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldClientCommonName, vs...))
}

// ClientCommonNameNotIn applies the NotIn predicate on the "client_common_name" field.
func ClientCommonNameNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldClientCommonName, vs...))
}

// ClientCommonNameGT applies the GT predicate on the "client_common_name" field.
func ClientCommonNameGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldClientCommonName, v))
}

// ClientCommonNameGTE applies the GTE predicate on the "client_common_name" field.
func ClientCommonNameGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldClientCommonName, v))
}

// ClientCommonNameLT applies the LT predicate on the "client_common_name" field.
func ClientCommonNameLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldClientCommonName, v))
}

// ClientCommonNameLTE applies the LTE predicate on the "client_common_name" field.
func ClientCommonNameLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldClientCommonName, v))
}

// ClientCommonNameContains applies the Contains predicate on the "client_common_name" field.
func ClientCommonNameContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldClientCommonName, v))
}

// ClientCommonNameHasPrefix applies the HasPrefix predicate on the "client_common_name" field.
func ClientCommonNameHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldClientCommonName, v))
}

// ClientCommonNameHasSuffix applies the HasSuffix predicate on the "client_common_name" field.
func ClientCommonNameHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldClientCommonName, v))
}

// ClientCommonNameIsNil applies the IsNil predicate on the "client_common_name" field.
func ClientCommonNameIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldClientCommonName))
}

// ClientCommonNameNotNil applies the NotNil predicate on the "client_common_name" field.
func ClientCommonNameNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldClientCommonName))
}

// ClientCommonNameEqualFold applies the EqualFold predicate on the "client_common_name" field.
func ClientCommonNameEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldClientCommonName, v))
}

// ClientCommonNameContainsFold applies the ContainsFold predicate on the "client_common_name" field.
func ClientCommonNameContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldClientCommonName, v))
}

// ClientOrganizationEQ applies the EQ predicate on the "client_organization" field.
func ClientOrganizationEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientOrganization, v))
}

// ClientOrganizationNEQ applies the NEQ predicate on the "client_organization" field.
func ClientOrganizationNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldClientOrganization, v))
}

// ClientOrganizationIn applies the In predicate on the "client_organization" field.
func ClientOrganizationIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldClientOrganization, vs...))
}

// ClientOrganizationNotIn applies the NotIn predicate on the "client_organization" field.
func ClientOrganizationNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldClientOrganization, vs...))
}

// ClientOrganizationGT applies the GT predicate on the "client_organization" field.
func ClientOrganizationGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldClientOrganization, v))
}

// ClientOrganizationGTE applies the GTE predicate on the "client_organization" field.
func ClientOrganizationGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldClientOrganization, v))
}

// ClientOrganizationLT applies the LT predicate on the "client_organization" field.
func ClientOrganizationLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldClientOrganization, v))
}

// ClientOrganizationLTE applies the LTE predicate on the "client_organization" field.
func ClientOrganizationLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldClientOrganization, v))
}

// ClientOrganizationContains applies the Contains predicate on the "client_organization" field.
func ClientOrganizationContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldClientOrganization, v))
}

// ClientOrganizationHasPrefix applies the HasPrefix predicate on the "client_organization" field.
func ClientOrganizationHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldClientOrganization, v))
}

// ClientOrganizationHasSuffix applies the HasSuffix predicate on the "client_organization" field.
func ClientOrganizationHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldClientOrganization, v))
}

// ClientOrganizationIsNil applies the IsNil predicate on the "client_organization" field.
func ClientOrganizationIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldClientOrganization))
}

// ClientOrganizationNotNil applies the NotNil predicate on the "client_organization" field.
func ClientOrganizationNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldClientOrganization))
}

// ClientOrganizationEqualFold applies the EqualFold predicate on the "client_organization" field.
func ClientOrganizationEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldClientOrganization, v))
}

// ClientOrganizationContainsFold applies the ContainsFold predicate on the "client_organization" field.
func ClientOrganizationContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldClientOrganization, v))
}

// ClientSerialNumberEQ applies the EQ predicate on the "client_serial_number" field.
func ClientSerialNumberEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldClientSerialNumber, v))
}

// ClientSerialNumberNEQ applies the NEQ predicate on the "client_serial_number" field.
func ClientSerialNumberNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldClientSerialNumber, v))
}

// ClientSerialNumberIn applies the In predicate on the "client_serial_number" field.
func ClientSerialNumberIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldClientSerialNumber, vs...))
}

// ClientSerialNumberNotIn applies the NotIn predicate on the "client_serial_number" field.
func ClientSerialNumberNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldClientSerialNumber, vs...))
}

// ClientSerialNumberGT applies the GT predicate on the "client_serial_number" field.
func ClientSerialNumberGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldClientSerialNumber, v))
}

// ClientSerialNumberGTE applies the GTE predicate on the "client_serial_number" field.
func ClientSerialNumberGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldClientSerialNumber, v))
}

// ClientSerialNumberLT applies the LT predicate on the "client_serial_number" field.
func ClientSerialNumberLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldClientSerialNumber, v))
}

// ClientSerialNumberLTE applies the LTE predicate on the "client_serial_number" field.
func ClientSerialNumberLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldClientSerialNumber, v))
}

// ClientSerialNumberContains applies the Contains predicate on the "client_serial_number" field.
func ClientSerialNumberContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldClientSerialNumber, v))
}

// ClientSerialNumberHasPrefix applies the HasPrefix predicate on the "client_serial_number" field.
func ClientSerialNumberHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldClientSerialNumber, v))
}

// ClientSerialNumberHasSuffix applies the HasSuffix predicate on the "client_serial_number" field.
func ClientSerialNumberHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldClientSerialNumber, v))
}

// ClientSerialNumberIsNil applies the IsNil predicate on the "client_serial_number" field.
func ClientSerialNumberIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldClientSerialNumber))
}

// ClientSerialNumberNotNil applies the NotNil predicate on the "client_serial_number" field.
func ClientSerialNumberNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldClientSerialNumber))
}

// ClientSerialNumberEqualFold applies the EqualFold predicate on the "client_serial_number" field.
func ClientSerialNumberEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldClientSerialNumber, v))
}

// ClientSerialNumberContainsFold applies the ContainsFold predicate on the "client_serial_number" field.
func ClientSerialNumberContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldClientSerialNumber, v))
}

// IsAuthenticatedEQ applies the EQ predicate on the "is_authenticated" field.
func IsAuthenticatedEQ(v bool) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldIsAuthenticated, v))
}

// IsAuthenticatedNEQ applies the NEQ predicate on the "is_authenticated" field.
func IsAuthenticatedNEQ(v bool) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldIsAuthenticated, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldSuccess, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v int32) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldErrorCode))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int64) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldLatencyMs, v))
}

// PeerAddressEQ applies the EQ predicate on the "peer_address" field.
func PeerAddressEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldPeerAddress, v))
}

// PeerAddressNEQ applies the NEQ predicate on the "peer_address" field.
func PeerAddressNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldPeerAddress, v))
}

// PeerAddressIn applies the In predicate on the "peer_address" field.
func PeerAddressIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldPeerAddress, vs...))
}

// PeerAddressNotIn applies the NotIn predicate on the "peer_address" field.
func PeerAddressNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldPeerAddress, vs...))
}

// PeerAddressGT applies the GT predicate on the "peer_address" field.
func PeerAddressGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldPeerAddress, v))
}

// PeerAddressGTE applies the GTE predicate on the "peer_address" field.
func PeerAddressGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldPeerAddress, v))
}

// PeerAddressLT applies the LT predicate on the "peer_address" field.
func PeerAddressLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldPeerAddress, v))
}

// PeerAddressLTE applies the LTE predicate on the "peer_address" field.
func PeerAddressLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldPeerAddress, v))
}

// PeerAddressContains applies the Contains predicate on the "peer_address" field.
func PeerAddressContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldPeerAddress, v))
}

// PeerAddressHasPrefix applies the HasPrefix predicate on the "peer_address" field.
func PeerAddressHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldPeerAddress, v))
}

// PeerAddressHasSuffix applies the HasSuffix predicate on the "peer_address" field.
func PeerAddressHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldPeerAddress, v))
}

// PeerAddressIsNil applies the IsNil predicate on the "peer_address" field.
func PeerAddressIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldPeerAddress))
}

// PeerAddressNotNil applies the NotNil predicate on the "peer_address" field.
func PeerAddressNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldPeerAddress))
}

// PeerAddressEqualFold applies the EqualFold predicate on the "peer_address" field.
func PeerAddressEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldPeerAddress, v))
}

// PeerAddressContainsFold applies the ContainsFold predicate on the "peer_address" field.
func PeerAddressContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldPeerAddress, v))
}

// GeoLocationIsNil applies the IsNil predicate on the "geo_location" field.
func GeoLocationIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldGeoLocation))
}

// GeoLocationNotNil applies the NotNil predicate on the "geo_location" field.
func GeoLocationNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldGeoLocation))
}

// LogHashEQ applies the EQ predicate on the "log_hash" field.
func LogHashEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldLogHash, v))
}

// LogHashNEQ applies the NEQ predicate on the "log_hash" field.
func LogHashNEQ(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldLogHash, v))
}

// LogHashIn applies the In predicate on the "log_hash" field.
func LogHashIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldLogHash, vs...))
}

// LogHashNotIn applies the NotIn predicate on the "log_hash" field.
func LogHashNotIn(vs ...string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldLogHash, vs...))
}

// LogHashGT applies the GT predicate on the "log_hash" field.
func LogHashGT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldLogHash, v))
}

// LogHashGTE applies the GTE predicate on the "log_hash" field.
func LogHashGTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldLogHash, v))
}

// LogHashLT applies the LT predicate on the "log_hash" field.
func LogHashLT(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldLogHash, v))
}

// LogHashLTE applies the LTE predicate on the "log_hash" field.
func LogHashLTE(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldLogHash, v))
}

// LogHashContains applies the Contains predicate on the "log_hash" field.
func LogHashContains(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContains(FieldLogHash, v))
}

// LogHashHasPrefix applies the HasPrefix predicate on the "log_hash" field.
func LogHashHasPrefix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasPrefix(FieldLogHash, v))
}

// LogHashHasSuffix applies the HasSuffix predicate on the "log_hash" field.
func LogHashHasSuffix(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldHasSuffix(FieldLogHash, v))
}

// LogHashIsNil applies the IsNil predicate on the "log_hash" field.
func LogHashIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldLogHash))
}

// LogHashNotNil applies the NotNil predicate on the "log_hash" field.
func LogHashNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldLogHash))
}

// LogHashEqualFold applies the EqualFold predicate on the "log_hash" field.
func LogHashEqualFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEqualFold(FieldLogHash, v))
}

// LogHashContainsFold applies the ContainsFold predicate on the "log_hash" field.
func LogHashContainsFold(v string) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldContainsFold(FieldLogHash, v))
}

// SignatureEQ applies the EQ predicate on the "signature" field.
func SignatureEQ(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldEQ(FieldSignature, v))
}

// SignatureNEQ applies the NEQ predicate on the "signature" field.
func SignatureNEQ(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNEQ(FieldSignature, v))
}

// SignatureIn applies the In predicate on the "signature" field.
func SignatureIn(vs ...[]byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIn(FieldSignature, vs...))
}

// SignatureNotIn applies the NotIn predicate on the "signature" field.
func SignatureNotIn(vs ...[]byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotIn(FieldSignature, vs...))
}

// SignatureGT applies the GT predicate on the "signature" field.
func SignatureGT(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGT(FieldSignature, v))
}

// SignatureGTE applies the GTE predicate on the "signature" field.
func SignatureGTE(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldGTE(FieldSignature, v))
}

// SignatureLT applies the LT predicate on the "signature" field.
func SignatureLT(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLT(FieldSignature, v))
}

// SignatureLTE applies the LTE predicate on the "signature" field.
func SignatureLTE(v []byte) predicate.AuditLog {
	return predicate.AuditLog(sql.FieldLTE(FieldSignature, v))
}

// SignatureIsNil applies the IsNil predicate on the "signature" field.
func SignatureIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldSignature))
}

// SignatureNotNil applies the NotNil predicate on the "signature" field.
func SignatureNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldSignature))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AuditLog {
	return predicate.AuditLog(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditLog) predicate.AuditLog {
	return predicate.AuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditLog) predicate.AuditLog {
	return predicate.AuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditLog) predicate.AuditLog {
	return predicate.AuditLog(sql.NotPredicates(p))
}
