// Code generated by ent, DO NOT EDIT.

package leaverequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-hr/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUpdateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUserID, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUserName, v))
}

// OrgUnitName applies equality check predicate on the "org_unit_name" field. It's identical to OrgUnitNameEQ.
func OrgUnitName(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldOrgUnitName, v))
}

// AbsenceTypeID applies equality check predicate on the "absence_type_id" field. It's identical to AbsenceTypeIDEQ.
func AbsenceTypeID(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldAbsenceTypeID, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldEndDate, v))
}

// Days applies equality check predicate on the "days" field. It's identical to DaysEQ.
func Days(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldDays, v))
}

// SigningRequestID applies equality check predicate on the "signing_request_id" field. It's identical to SigningRequestIDEQ.
func SigningRequestID(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldSigningRequestID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReason, v))
}

// ReviewNotes applies equality check predicate on the "review_notes" field. It's identical to ReviewNotesEQ.
func ReviewNotes(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewNotes, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewerName applies equality check predicate on the "reviewer_name" field. It's identical to ReviewerNameEQ.
func ReviewerName(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewerName, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldNotes, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldCreateBy))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldUpdateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldTenantID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldUserID, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameIsNil applies the IsNil predicate on the "user_name" field.
func UserNameIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldUserName))
}

// UserNameNotNil applies the NotNil predicate on the "user_name" field.
func UserNameNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldUserName))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldUserName, v))
}

// OrgUnitNameEQ applies the EQ predicate on the "org_unit_name" field.
func OrgUnitNameEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldOrgUnitName, v))
}

// OrgUnitNameNEQ applies the NEQ predicate on the "org_unit_name" field.
func OrgUnitNameNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldOrgUnitName, v))
}

// OrgUnitNameIn applies the In predicate on the "org_unit_name" field.
func OrgUnitNameIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldOrgUnitName, vs...))
}

// OrgUnitNameNotIn applies the NotIn predicate on the "org_unit_name" field.
func OrgUnitNameNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldOrgUnitName, vs...))
}

// OrgUnitNameGT applies the GT predicate on the "org_unit_name" field.
func OrgUnitNameGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldOrgUnitName, v))
}

// OrgUnitNameGTE applies the GTE predicate on the "org_unit_name" field.
func OrgUnitNameGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldOrgUnitName, v))
}

// OrgUnitNameLT applies the LT predicate on the "org_unit_name" field.
func OrgUnitNameLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldOrgUnitName, v))
}

// OrgUnitNameLTE applies the LTE predicate on the "org_unit_name" field.
func OrgUnitNameLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldOrgUnitName, v))
}

// OrgUnitNameContains applies the Contains predicate on the "org_unit_name" field.
func OrgUnitNameContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldOrgUnitName, v))
}

// OrgUnitNameHasPrefix applies the HasPrefix predicate on the "org_unit_name" field.
func OrgUnitNameHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldOrgUnitName, v))
}

// OrgUnitNameHasSuffix applies the HasSuffix predicate on the "org_unit_name" field.
func OrgUnitNameHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldOrgUnitName, v))
}

// OrgUnitNameIsNil applies the IsNil predicate on the "org_unit_name" field.
func OrgUnitNameIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldOrgUnitName))
}

// OrgUnitNameNotNil applies the NotNil predicate on the "org_unit_name" field.
func OrgUnitNameNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldOrgUnitName))
}

// OrgUnitNameEqualFold applies the EqualFold predicate on the "org_unit_name" field.
func OrgUnitNameEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldOrgUnitName, v))
}

// OrgUnitNameContainsFold applies the ContainsFold predicate on the "org_unit_name" field.
func OrgUnitNameContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldOrgUnitName, v))
}

// AbsenceTypeIDEQ applies the EQ predicate on the "absence_type_id" field.
func AbsenceTypeIDEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDNEQ applies the NEQ predicate on the "absence_type_id" field.
func AbsenceTypeIDNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDIn applies the In predicate on the "absence_type_id" field.
func AbsenceTypeIDIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldAbsenceTypeID, vs...))
}

// AbsenceTypeIDNotIn applies the NotIn predicate on the "absence_type_id" field.
func AbsenceTypeIDNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldAbsenceTypeID, vs...))
}

// AbsenceTypeIDGT applies the GT predicate on the "absence_type_id" field.
func AbsenceTypeIDGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDGTE applies the GTE predicate on the "absence_type_id" field.
func AbsenceTypeIDGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDLT applies the LT predicate on the "absence_type_id" field.
func AbsenceTypeIDLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDLTE applies the LTE predicate on the "absence_type_id" field.
func AbsenceTypeIDLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDContains applies the Contains predicate on the "absence_type_id" field.
func AbsenceTypeIDContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDHasPrefix applies the HasPrefix predicate on the "absence_type_id" field.
func AbsenceTypeIDHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDHasSuffix applies the HasSuffix predicate on the "absence_type_id" field.
func AbsenceTypeIDHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDEqualFold applies the EqualFold predicate on the "absence_type_id" field.
func AbsenceTypeIDEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldAbsenceTypeID, v))
}

// AbsenceTypeIDContainsFold applies the ContainsFold predicate on the "absence_type_id" field.
func AbsenceTypeIDContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldAbsenceTypeID, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldEndDate, v))
}

// DaysEQ applies the EQ predicate on the "days" field.
func DaysEQ(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldDays, v))
}

// DaysNEQ applies the NEQ predicate on the "days" field.
func DaysNEQ(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldDays, v))
}

// DaysIn applies the In predicate on the "days" field.
func DaysIn(vs ...float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldDays, vs...))
}

// DaysNotIn applies the NotIn predicate on the "days" field.
func DaysNotIn(vs ...float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldDays, vs...))
}

// DaysGT applies the GT predicate on the "days" field.
func DaysGT(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldDays, v))
}

// DaysGTE applies the GTE predicate on the "days" field.
func DaysGTE(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldDays, v))
}

// DaysLT applies the LT predicate on the "days" field.
func DaysLT(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldDays, v))
}

// DaysLTE applies the LTE predicate on the "days" field.
func DaysLTE(v float64) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldDays, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// SigningRequestIDEQ applies the EQ predicate on the "signing_request_id" field.
func SigningRequestIDEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldSigningRequestID, v))
}

// SigningRequestIDNEQ applies the NEQ predicate on the "signing_request_id" field.
func SigningRequestIDNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldSigningRequestID, v))
}

// SigningRequestIDIn applies the In predicate on the "signing_request_id" field.
func SigningRequestIDIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldSigningRequestID, vs...))
}

// SigningRequestIDNotIn applies the NotIn predicate on the "signing_request_id" field.
func SigningRequestIDNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldSigningRequestID, vs...))
}

// SigningRequestIDGT applies the GT predicate on the "signing_request_id" field.
func SigningRequestIDGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldSigningRequestID, v))
}

// SigningRequestIDGTE applies the GTE predicate on the "signing_request_id" field.
func SigningRequestIDGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldSigningRequestID, v))
}

// SigningRequestIDLT applies the LT predicate on the "signing_request_id" field.
func SigningRequestIDLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldSigningRequestID, v))
}

// SigningRequestIDLTE applies the LTE predicate on the "signing_request_id" field.
func SigningRequestIDLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldSigningRequestID, v))
}

// SigningRequestIDContains applies the Contains predicate on the "signing_request_id" field.
func SigningRequestIDContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldSigningRequestID, v))
}

// SigningRequestIDHasPrefix applies the HasPrefix predicate on the "signing_request_id" field.
func SigningRequestIDHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldSigningRequestID, v))
}

// SigningRequestIDHasSuffix applies the HasSuffix predicate on the "signing_request_id" field.
func SigningRequestIDHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldSigningRequestID, v))
}

// SigningRequestIDIsNil applies the IsNil predicate on the "signing_request_id" field.
func SigningRequestIDIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldSigningRequestID))
}

// SigningRequestIDNotNil applies the NotNil predicate on the "signing_request_id" field.
func SigningRequestIDNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldSigningRequestID))
}

// SigningRequestIDEqualFold applies the EqualFold predicate on the "signing_request_id" field.
func SigningRequestIDEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldSigningRequestID, v))
}

// SigningRequestIDContainsFold applies the ContainsFold predicate on the "signing_request_id" field.
func SigningRequestIDContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldSigningRequestID, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldReason, v))
}

// ReviewNotesEQ applies the EQ predicate on the "review_notes" field.
func ReviewNotesEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewNotes, v))
}

// ReviewNotesNEQ applies the NEQ predicate on the "review_notes" field.
func ReviewNotesNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldReviewNotes, v))
}

// ReviewNotesIn applies the In predicate on the "review_notes" field.
func ReviewNotesIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldReviewNotes, vs...))
}

// ReviewNotesNotIn applies the NotIn predicate on the "review_notes" field.
func ReviewNotesNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldReviewNotes, vs...))
}

// ReviewNotesGT applies the GT predicate on the "review_notes" field.
func ReviewNotesGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldReviewNotes, v))
}

// ReviewNotesGTE applies the GTE predicate on the "review_notes" field.
func ReviewNotesGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldReviewNotes, v))
}

// ReviewNotesLT applies the LT predicate on the "review_notes" field.
func ReviewNotesLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldReviewNotes, v))
}

// ReviewNotesLTE applies the LTE predicate on the "review_notes" field.
func ReviewNotesLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldReviewNotes, v))
}

// ReviewNotesContains applies the Contains predicate on the "review_notes" field.
func ReviewNotesContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldReviewNotes, v))
}

// ReviewNotesHasPrefix applies the HasPrefix predicate on the "review_notes" field.
func ReviewNotesHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldReviewNotes, v))
}

// ReviewNotesHasSuffix applies the HasSuffix predicate on the "review_notes" field.
func ReviewNotesHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldReviewNotes, v))
}

// ReviewNotesIsNil applies the IsNil predicate on the "review_notes" field.
func ReviewNotesIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldReviewNotes))
}

// ReviewNotesNotNil applies the NotNil predicate on the "review_notes" field.
func ReviewNotesNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldReviewNotes))
}

// ReviewNotesEqualFold applies the EqualFold predicate on the "review_notes" field.
func ReviewNotesEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldReviewNotes, v))
}

// ReviewNotesContainsFold applies the ContainsFold predicate on the "review_notes" field.
func ReviewNotesContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldReviewNotes, v))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v uint32) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewerNameEQ applies the EQ predicate on the "reviewer_name" field.
func ReviewerNameEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewerName, v))
}

// ReviewerNameNEQ applies the NEQ predicate on the "reviewer_name" field.
func ReviewerNameNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldReviewerName, v))
}

// ReviewerNameIn applies the In predicate on the "reviewer_name" field.
func ReviewerNameIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldReviewerName, vs...))
}

// ReviewerNameNotIn applies the NotIn predicate on the "reviewer_name" field.
func ReviewerNameNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldReviewerName, vs...))
}

// ReviewerNameGT applies the GT predicate on the "reviewer_name" field.
func ReviewerNameGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldReviewerName, v))
}

// ReviewerNameGTE applies the GTE predicate on the "reviewer_name" field.
func ReviewerNameGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldReviewerName, v))
}

// ReviewerNameLT applies the LT predicate on the "reviewer_name" field.
func ReviewerNameLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldReviewerName, v))
}

// ReviewerNameLTE applies the LTE predicate on the "reviewer_name" field.
func ReviewerNameLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldReviewerName, v))
}

// ReviewerNameContains applies the Contains predicate on the "reviewer_name" field.
func ReviewerNameContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldReviewerName, v))
}

// ReviewerNameHasPrefix applies the HasPrefix predicate on the "reviewer_name" field.
func ReviewerNameHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldReviewerName, v))
}

// ReviewerNameHasSuffix applies the HasSuffix predicate on the "reviewer_name" field.
func ReviewerNameHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldReviewerName, v))
}

// ReviewerNameIsNil applies the IsNil predicate on the "reviewer_name" field.
func ReviewerNameIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldReviewerName))
}

// ReviewerNameNotNil applies the NotNil predicate on the "reviewer_name" field.
func ReviewerNameNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldReviewerName))
}

// ReviewerNameEqualFold applies the EqualFold predicate on the "reviewer_name" field.
func ReviewerNameEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldReviewerName, v))
}

// ReviewerNameContainsFold applies the ContainsFold predicate on the "reviewer_name" field.
func ReviewerNameContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldReviewerName, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldReviewedAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldContainsFold(FieldNotes, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.FieldNotNull(FieldMetadata))
}

// HasAbsenceType applies the HasEdge predicate on the "absence_type" edge.
func HasAbsenceType() predicate.LeaveRequest {
	return predicate.LeaveRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AbsenceTypeTable, AbsenceTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAbsenceTypeWith applies the HasEdge predicate on the "absence_type" edge with a given conditions (other predicates).
func HasAbsenceTypeWith(preds ...predicate.AbsenceType) predicate.LeaveRequest {
	return predicate.LeaveRequest(func(s *sql.Selector) {
		step := newAbsenceTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LeaveRequest) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LeaveRequest) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LeaveRequest) predicate.LeaveRequest {
	return predicate.LeaveRequest(sql.NotPredicates(p))
}
