// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HrAbsenceTypesColumns holds the columns for the "hr_absence_types" table.
	HrAbsenceTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "Unique identifier"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Absence type name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Description"},
		{Name: "color", Type: field.TypeString, Nullable: true, Size: 7, Comment: "Hex color for calendar display"},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 100, Comment: "Lucide icon name"},
		{Name: "deducts_from_allowance", Type: field.TypeBool, Comment: "Whether this type consumes leave days", Default: true},
		{Name: "requires_approval", Type: field.TypeBool, Comment: "Whether requests need HR admin approval", Default: true},
		{Name: "is_active", Type: field.TypeBool, Comment: "Whether this type is available for new requests", Default: true},
		{Name: "sort_order", Type: field.TypeInt, Comment: "Display sort order", Default: 0},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Custom metadata (JSON)"},
		{Name: "requires_signing", Type: field.TypeBool, Comment: "Whether this type requires document signing", Default: false},
		{Name: "signing_template_id", Type: field.TypeString, Nullable: true, Comment: "Paperless signing template ID"},
	}
	// HrAbsenceTypesTable holds the schema information for the "hr_absence_types" table.
	HrAbsenceTypesTable = &schema.Table{
		Name:       "hr_absence_types",
		Columns:    HrAbsenceTypesColumns,
		PrimaryKey: []*schema.Column{HrAbsenceTypesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_hr_abstype_tenant_name",
				Unique:  true,
				Columns: []*schema.Column{HrAbsenceTypesColumns[6], HrAbsenceTypesColumns[7]},
			},
			{
				Name:    "idx_hr_abstype_tenant",
				Unique:  false,
				Columns: []*schema.Column{HrAbsenceTypesColumns[6]},
			},
		},
	}
	// HrAuditLogsColumns holds the columns for the "hr_audit_logs" table.
	HrAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "audit_id", Type: field.TypeString, Unique: true, Comment: "Unique audit log identifier (UUID)"},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Comment: "Request ID from metadata"},
		{Name: "operation", Type: field.TypeString, Comment: "gRPC operation path"},
		{Name: "service_name", Type: field.TypeString, Comment: "Service name", Default: "hr-service"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "Client ID from certificate CN"},
		{Name: "client_common_name", Type: field.TypeString, Nullable: true, Comment: "Client certificate common name"},
		{Name: "client_organization", Type: field.TypeString, Nullable: true, Comment: "Client certificate organization"},
		{Name: "client_serial_number", Type: field.TypeString, Nullable: true, Comment: "Client certificate serial number"},
		{Name: "is_authenticated", Type: field.TypeBool, Comment: "Whether the client was authenticated via mTLS", Default: false},
		{Name: "success", Type: field.TypeBool, Comment: "Whether the operation succeeded", Default: true},
		{Name: "error_code", Type: field.TypeInt32, Nullable: true, Comment: "Error code if failed"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Comment: "Error message if failed"},
		{Name: "latency_ms", Type: field.TypeInt64, Comment: "Operation latency in milliseconds", Default: 0},
		{Name: "peer_address", Type: field.TypeString, Nullable: true, Comment: "Client IP address"},
		{Name: "geo_location", Type: field.TypeJSON, Nullable: true, Comment: "Geographic location info"},
		{Name: "log_hash", Type: field.TypeString, Nullable: true, Comment: "SHA-256 hash of the log content"},
		{Name: "signature", Type: field.TypeBytes, Nullable: true, Comment: "ECDSA signature for integrity verification"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Additional metadata"},
	}
	// HrAuditLogsTable holds the schema information for the "hr_audit_logs" table.
	HrAuditLogsTable = &schema.Table{
		Name:       "hr_audit_logs",
		Columns:    HrAuditLogsColumns,
		PrimaryKey: []*schema.Column{HrAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "hr_auditlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[4]},
			},
			{
				Name:    "hr_auditlog_tenant_client",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[4], HrAuditLogsColumns[9]},
			},
			{
				Name:    "hr_auditlog_tenant_operation",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[4], HrAuditLogsColumns[7]},
			},
			{
				Name:    "hr_auditlog_tenant_success",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[4], HrAuditLogsColumns[14]},
			},
			{
				Name:    "hr_auditlog_operation",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[7]},
			},
			{
				Name:    "hr_auditlog_client_id",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[9]},
			},
			{
				Name:    "hr_auditlog_success",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[14]},
			},
			{
				Name:    "hr_auditlog_peer_address",
				Unique:  false,
				Columns: []*schema.Column{HrAuditLogsColumns[18]},
			},
		},
	}
	// HrLeaveAllowancesColumns holds the columns for the "hr_leave_allowances" table.
	HrLeaveAllowancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "Unique identifier"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "user_id", Type: field.TypeUint32, Comment: "FK to Portal User"},
		{Name: "user_name", Type: field.TypeString, Nullable: true, Comment: "Denormalized user display name", Default: ""},
		{Name: "year", Type: field.TypeInt, Comment: "Calendar year"},
		{Name: "total_days", Type: field.TypeFloat64, Comment: "Total allowed days (supports half-days)"},
		{Name: "used_days", Type: field.TypeFloat64, Comment: "Consumed days", Default: 0},
		{Name: "carried_over", Type: field.TypeFloat64, Comment: "Carried from previous year", Default: 0},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Notes"},
		{Name: "absence_type_id", Type: field.TypeString, Comment: "FK to AbsenceType"},
	}
	// HrLeaveAllowancesTable holds the schema information for the "hr_leave_allowances" table.
	HrLeaveAllowancesTable = &schema.Table{
		Name:       "hr_leave_allowances",
		Columns:    HrLeaveAllowancesColumns,
		PrimaryKey: []*schema.Column{HrLeaveAllowancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hr_leave_allowances_hr_absence_types_leave_allowances",
				Columns:    []*schema.Column{HrLeaveAllowancesColumns[14]},
				RefColumns: []*schema.Column{HrAbsenceTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "idx_hr_allowance_tenant_user_type_year",
				Unique:  true,
				Columns: []*schema.Column{HrLeaveAllowancesColumns[6], HrLeaveAllowancesColumns[7], HrLeaveAllowancesColumns[14], HrLeaveAllowancesColumns[9]},
			},
			{
				Name:    "idx_hr_allowance_tenant",
				Unique:  false,
				Columns: []*schema.Column{HrLeaveAllowancesColumns[6]},
			},
		},
	}
	// HrLeaveRequestsColumns holds the columns for the "hr_leave_requests" table.
	HrLeaveRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "Unique identifier"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "user_id", Type: field.TypeUint32, Comment: "FK to Portal User"},
		{Name: "user_name", Type: field.TypeString, Nullable: true, Comment: "Denormalized user display name", Default: ""},
		{Name: "org_unit_name", Type: field.TypeString, Nullable: true, Comment: "Denormalized org unit name for grouping", Default: ""},
		{Name: "start_date", Type: field.TypeTime, Comment: "Start date of absence"},
		{Name: "end_date", Type: field.TypeTime, Comment: "End date of absence"},
		{Name: "days", Type: field.TypeFloat64, Comment: "Calculated business days"},
		{Name: "status", Type: field.TypeEnum, Comment: "Request status", Enums: []string{"pending", "approved", "rejected", "cancelled"}, Default: "pending"},
		{Name: "reason", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "User's reason for request"},
		{Name: "review_notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "HR admin's review notes"},
		{Name: "reviewed_by", Type: field.TypeUint32, Nullable: true, Comment: "User ID of reviewer", Default: 0},
		{Name: "reviewer_name", Type: field.TypeString, Nullable: true, Comment: "Denormalized reviewer display name", Default: ""},
		{Name: "reviewed_at", Type: field.TypeTime, Nullable: true, Comment: "When the request was reviewed"},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Additional notes"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Custom metadata (JSON)"},
		{Name: "absence_type_id", Type: field.TypeString, Comment: "FK to AbsenceType"},
	}
	// HrLeaveRequestsTable holds the schema information for the "hr_leave_requests" table.
	HrLeaveRequestsTable = &schema.Table{
		Name:       "hr_leave_requests",
		Columns:    HrLeaveRequestsColumns,
		PrimaryKey: []*schema.Column{HrLeaveRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hr_leave_requests_hr_absence_types_leave_requests",
				Columns:    []*schema.Column{HrLeaveRequestsColumns[21]},
				RefColumns: []*schema.Column{HrAbsenceTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "idx_hr_leavereq_tenant_user_start",
				Unique:  false,
				Columns: []*schema.Column{HrLeaveRequestsColumns[6], HrLeaveRequestsColumns[7], HrLeaveRequestsColumns[10]},
			},
			{
				Name:    "idx_hr_leavereq_tenant_status",
				Unique:  false,
				Columns: []*schema.Column{HrLeaveRequestsColumns[6], HrLeaveRequestsColumns[13]},
			},
			{
				Name:    "idx_hr_leavereq_tenant",
				Unique:  false,
				Columns: []*schema.Column{HrLeaveRequestsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HrAbsenceTypesTable,
		HrAuditLogsTable,
		HrLeaveAllowancesTable,
		HrLeaveRequestsTable,
	}
)

func init() {
	HrAbsenceTypesTable.Annotation = &entsql.Annotation{
		Table: "hr_absence_types",
	}
	HrAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "hr_audit_logs",
	}
	HrLeaveAllowancesTable.ForeignKeys[0].RefTable = HrAbsenceTypesTable
	HrLeaveAllowancesTable.Annotation = &entsql.Annotation{
		Table: "hr_leave_allowances",
	}
	HrLeaveRequestsTable.ForeignKeys[0].RefTable = HrAbsenceTypesTable
	HrLeaveRequestsTable.Annotation = &entsql.Annotation{
		Table: "hr_leave_requests",
	}
}
