// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-hr/internal/cert"
	"github.com/go-tangra/go-tangra-hr/internal/data"
	"github.com/go-tangra/go-tangra-hr/internal/server"
	"github.com/go-tangra/go-tangra-hr/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	absenceTypeRepo := data.NewAbsenceTypeRepo(context, entClient)
	leaveRequestRepo := data.NewLeaveRequestRepo(context, entClient)
	systemService := service.NewSystemService(context, absenceTypeRepo, leaveRequestRepo)
	absenceTypeService := service.NewAbsenceTypeService(context, absenceTypeRepo)
	leaveAllowanceRepo := data.NewLeaveAllowanceRepo(context, entClient)
	leaveService := service.NewLeaveService(context, leaveRequestRepo, leaveAllowanceRepo, absenceTypeRepo)
	allowanceService := service.NewAllowanceService(context, leaveAllowanceRepo, absenceTypeRepo)
	grpcServer := server.NewGRPCServer(context, certManager, auditLogRepo, systemService, absenceTypeService, leaveService, allowanceService)
	httpServer := server.NewHTTPServer(context)
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
