// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	gocontext "context"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-common/viewer"
	"github.com/go-tangra/go-tangra-hr/internal/cert"
	"github.com/go-tangra/go-tangra-hr/internal/client"
	"github.com/go-tangra/go-tangra-hr/internal/data"
	"github.com/go-tangra/go-tangra-hr/internal/event"
	"github.com/go-tangra/go-tangra-hr/internal/metrics"
	"github.com/go-tangra/go-tangra-hr/internal/server"
	"github.com/go-tangra/go-tangra-hr/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	absenceTypeRepo := data.NewAbsenceTypeRepo(context, entClient)
	leaveRequestRepo := data.NewLeaveRequestRepo(context, entClient)
	systemService := service.NewSystemService(context, absenceTypeRepo, leaveRequestRepo)
	absenceTypeService := service.NewAbsenceTypeService(context, absenceTypeRepo)
	leaveAllowanceRepo := data.NewLeaveAllowanceRepo(context, entClient)
	registrationClient, err := client.NewRegistrationClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	moduleDialer := client.NewModuleDialer(context, registrationClient)
	paperlessClient, cleanup2, err := client.NewPaperlessClient(context, moduleDialer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationClient, cleanup3, err := client.NewNotificationClient(context, moduleDialer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	leaveService := service.NewLeaveService(context, leaveRequestRepo, leaveAllowanceRepo, absenceTypeRepo, paperlessClient, notificationClient)
	allowancePoolRepo := data.NewAllowancePoolRepo(context, entClient)
	allowanceService := service.NewAllowanceService(context, leaveAllowanceRepo, absenceTypeRepo, allowancePoolRepo)
	allowancePoolService := service.NewAllowancePoolService(context, allowancePoolRepo, absenceTypeRepo)
	adminClient, cleanup4, err := client.NewAdminClient(context, certManager)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(context, adminClient)
	grpcServer := server.NewGRPCServer(context, certManager, collector, auditLogRepo, systemService, absenceTypeService, leaveService, allowanceService, allowancePoolService, userService)
	httpServer := server.NewHTTPServer(context)
	redisClient, cleanup5, err := data.NewRedisClient(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := event.NewHandler(context, leaveRequestRepo, leaveAllowanceRepo, absenceTypeRepo)
	subscriber := event.NewSubscriber(context, redisClient, handler)

	// Seed Prometheus metrics from database
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	seedCtx := viewer.NewSystemViewerContext(gocontext.Background())
	collector.Seed(seedCtx, statisticsRepo)

	app := newApp(context, grpcServer, httpServer, subscriber, registrationClient)
	return app, func() {
		collector.Stop(gocontext.Background())
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
